import { CreateUserData, CreateUserVariables, UpdateUserData, UpdateUserVariables, CreateSubjectData, CreateSubjectVariables, UpdateSubjectData, UpdateSubjectVariables, DeactivateSubjectData, DeactivateSubjectVariables, ReactivateSubjectData, ReactivateSubjectVariables, CreateUnitData, CreateUnitVariables, UpdateUnitData, UpdateUnitVariables, DeactivateUnitData, DeactivateUnitVariables, ReactivateUnitData, ReactivateUnitVariables, CreateTopicData, CreateTopicVariables, UpdateTopicData, UpdateTopicVariables, DeactivateTopicData, DeactivateTopicVariables, ReactivateTopicData, ReactivateTopicVariables, CreateLevelCategoryData, CreateLevelCategoryVariables, UpdateLevelCategoryData, UpdateLevelCategoryVariables, DeactivateLevelCategoryData, DeactivateLevelCategoryVariables, ReactivateLevelCategoryData, ReactivateLevelCategoryVariables, CreateEducationalLevelData, CreateEducationalLevelVariables, UpdateEducationalLevelData, UpdateEducationalLevelVariables, DeactivateEducationalLevelData, DeactivateEducationalLevelVariables, ReactivateEducationalLevelData, ReactivateEducationalLevelVariables, CreateCourseData, CreateCourseVariables, UpdateCourseData, UpdateCourseVariables, DeactivateCourseData, DeactivateCourseVariables, ReactivateCourseData, ReactivateCourseVariables, CreateQuestionData, CreateQuestionVariables, CreateQuestionVersionData, CreateQuestionVersionVariables, UpdateQuestionData, UpdateQuestionVariables, DeactivateQuestionData, DeactivateQuestionVariables, ReactivateQuestionData, ReactivateQuestionVariables, CreateQuestionOptionData, CreateQuestionOptionVariables, UpdateQuestionOptionData, UpdateQuestionOptionVariables, DeleteQuestionOptionData, DeleteQuestionOptionVariables, CreateQuestionTypeData, CreateQuestionTypeVariables, UpdateQuestionTypeData, UpdateQuestionTypeVariables, DeactivateQuestionTypeData, DeactivateQuestionTypeVariables, ReactivateQuestionTypeData, ReactivateQuestionTypeVariables, CreateDifficultyData, CreateDifficultyVariables, DeactivateDifficultyData, DeactivateDifficultyVariables, ReactivateDifficultyData, ReactivateDifficultyVariables, CreateTaxonomyData, CreateTaxonomyVariables, UpdateTaxonomyData, UpdateTaxonomyVariables, DeactivateTaxonomyData, DeactivateTaxonomyVariables, ReactivateTaxonomyData, ReactivateTaxonomyVariables, CreateEvaluationData, CreateEvaluationVariables, UpdateEvaluationData, UpdateEvaluationVariables, UpdateEvaluationStateData, UpdateEvaluationStateVariables, DeactivateEvaluationData, DeactivateEvaluationVariables, ReactivateEvaluationData, ReactivateEvaluationVariables, AddQuestionToEvaluationData, AddQuestionToEvaluationVariables, UpdateEvaluationQuestionData, UpdateEvaluationQuestionVariables, RemoveQuestionFromEvaluationData, RemoveQuestionFromEvaluationVariables, AssignEvaluationToCourseData, AssignEvaluationToCourseVariables, RemoveEvaluationFromCourseData, RemoveEvaluationFromCourseVariables, CreateStudentData, CreateStudentVariables, UpdateStudentData, UpdateStudentVariables, DeactivateStudentData, DeactivateStudentVariables, ReactivateStudentData, ReactivateStudentVariables, EnrollStudentInCourseData, EnrollStudentInCourseVariables, UpdateCourseStudentData, UpdateCourseStudentVariables, UnenrollStudentFromCourseData, UnenrollStudentFromCourseVariables, ReenrollStudentInCourseData, ReenrollStudentInCourseVariables, CreateStudentEvaluationData, CreateStudentEvaluationVariables, UpdateStudentEvaluationStateData, UpdateStudentEvaluationStateVariables, StartStudentEvaluationData, StartStudentEvaluationVariables, CompleteStudentEvaluationData, CompleteStudentEvaluationVariables, GradeStudentEvaluationData, GradeStudentEvaluationVariables, UpdateStudentEvaluationScoreData, UpdateStudentEvaluationScoreVariables, AddQuestionToStudentEvaluationData, AddQuestionToStudentEvaluationVariables, GradeStudentQuestionData, GradeStudentQuestionVariables, UpdateStudentQuestionPositionData, UpdateStudentQuestionPositionVariables, RemoveQuestionFromStudentEvaluationData, RemoveQuestionFromStudentEvaluationVariables, RegisterStudentAnswerData, RegisterStudentAnswerVariables, RemoveStudentAnswerData, RemoveStudentAnswerVariables, GetUserByEmailData, GetUserByEmailVariables, GetUserByIdData, GetUserByIdVariables, ListSubjectsData, GetSubjectData, GetSubjectVariables, ListUnitsData, GetUnitData, GetUnitVariables, ListTopicsData, GetTopicData, GetTopicVariables, ListLevelCategoriesData, GetLevelCategoryData, GetLevelCategoryVariables, ListEducationalLevelsData, GetEducationalLevelData, GetEducationalLevelVariables, GetLevelsByCategoryData, GetLevelsByCategoryVariables, ListCoursesData, ListCoursesVariables, GetCourseData, GetCourseVariables, GetCoursesByUserData, GetCoursesByUserVariables, GetCoursesByLevelData, GetCoursesByLevelVariables, ListDifficultiesData, GetDifficultyData, GetDifficultyVariables, ListQuestionTypesData, GetQuestionTypeData, GetQuestionTypeVariables, GetQuestionTypeByCodeData, GetQuestionTypeByCodeVariables, ListTaxonomiesData, GetTaxonomyData, GetTaxonomyVariables, GetTaxonomyByCodeData, GetTaxonomyByCodeVariables, ListTaxonomiesByLevelData, ListQuestionsByUserData, ListQuestionsByUserVariables, GetDashboardQuestionsData, GetDashboardQuestionsVariables, GetDashboardSystemDataData, GetQuestionData, GetQuestionVariables, ListPublicQuestionsData, ListPublicQuestionsByDifficultyData, ListPublicQuestionsByDifficultyVariables, ListPublicQuestionsByTypeData, ListPublicQuestionsByTypeVariables, GetQuestionOptionsData, GetQuestionOptionsVariables, GetAllCoursesByUserData, GetAllCoursesByUserVariables, GetCourseByCodeData, GetCourseByCodeVariables, GetCoursesByInstitutionData, GetCoursesByInstitutionVariables, GetCoursesByEducationalLevelData, GetCoursesByEducationalLevelVariables, GetEvaluationByIdData, GetEvaluationByIdVariables, GetAllEvaluationsByUserData, GetAllEvaluationsByUserVariables, GetEvaluationsByDateRangeData, GetEvaluationsByDateRangeVariables, GetEvaluationsByStateData, GetEvaluationsByStateVariables, GetEvaluationsBySubjectData, GetEvaluationsBySubjectVariables, GetEvaluationsByCourseData, GetEvaluationsByCourseVariables, GetEvaluationFullDetailData, GetEvaluationFullDetailVariables, GetEvaluationQuestionsData, GetEvaluationQuestionsVariables, GetAllStudentsByUserData, GetAllStudentsByUserVariables, GetStudentByIdData, GetStudentByIdVariables, GetStudentByIdentifierData, GetStudentByIdentifierVariables, GetStudentsByFirstNameData, GetStudentsByFirstNameVariables, GetStudentsByLastNameData, GetStudentsByLastNameVariables, GetStudentsByCourseData, GetStudentsByCourseVariables, GetCourseStudentsDetailData, GetCourseStudentsDetailVariables, GetCourseStudentsWithDetailsData, GetCourseStudentsWithDetailsVariables, GetStudentEvaluationByIdData, GetStudentEvaluationByIdVariables, GetStudentEvaluationsByStudentIdData, GetStudentEvaluationsByStudentIdVariables, GetStudentEvaluationsByIdentifierData, GetStudentEvaluationsByIdentifierVariables, GetStudentEvaluationsByFirstNameData, GetStudentEvaluationsByFirstNameVariables, GetStudentEvaluationsByLastNameData, GetStudentEvaluationsByLastNameVariables, GetStudentEvaluationQuestionsData, GetStudentEvaluationQuestionsVariables, GetStudentAnswerOptionsData, GetStudentAnswerOptionsVariables, GetStudentEvaluationsByCourseEvaluationData, GetStudentEvaluationsByCourseEvaluationVariables, GetStudentEvaluationsByCourseStudentData, GetStudentEvaluationsByCourseStudentVariables, GetStudentEvaluationFullDetailData, GetStudentEvaluationFullDetailVariables, GetCourseEvaluationsByUserData, GetCourseEvaluationsByUserVariables, GetCourseEvaluationByIdData, GetCourseEvaluationByIdVariables, GetEvaluationsForCourseData, GetEvaluationsForCourseVariables, GetCoursesForEvaluationData, GetCoursesForEvaluationVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useCreateUser(options?: useDataConnectMutationOptions<CreateUserData, FirebaseError, CreateUserVariables>): UseDataConnectMutationResult<CreateUserData, CreateUserVariables>;
export function useCreateUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserData, FirebaseError, CreateUserVariables>): UseDataConnectMutationResult<CreateUserData, CreateUserVariables>;

export function useUpdateUser(options?: useDataConnectMutationOptions<UpdateUserData, FirebaseError, UpdateUserVariables>): UseDataConnectMutationResult<UpdateUserData, UpdateUserVariables>;
export function useUpdateUser(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUserData, FirebaseError, UpdateUserVariables>): UseDataConnectMutationResult<UpdateUserData, UpdateUserVariables>;

export function useCreateSubject(options?: useDataConnectMutationOptions<CreateSubjectData, FirebaseError, CreateSubjectVariables>): UseDataConnectMutationResult<CreateSubjectData, CreateSubjectVariables>;
export function useCreateSubject(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSubjectData, FirebaseError, CreateSubjectVariables>): UseDataConnectMutationResult<CreateSubjectData, CreateSubjectVariables>;

export function useUpdateSubject(options?: useDataConnectMutationOptions<UpdateSubjectData, FirebaseError, UpdateSubjectVariables>): UseDataConnectMutationResult<UpdateSubjectData, UpdateSubjectVariables>;
export function useUpdateSubject(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSubjectData, FirebaseError, UpdateSubjectVariables>): UseDataConnectMutationResult<UpdateSubjectData, UpdateSubjectVariables>;

export function useDeactivateSubject(options?: useDataConnectMutationOptions<DeactivateSubjectData, FirebaseError, DeactivateSubjectVariables>): UseDataConnectMutationResult<DeactivateSubjectData, DeactivateSubjectVariables>;
export function useDeactivateSubject(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateSubjectData, FirebaseError, DeactivateSubjectVariables>): UseDataConnectMutationResult<DeactivateSubjectData, DeactivateSubjectVariables>;

export function useReactivateSubject(options?: useDataConnectMutationOptions<ReactivateSubjectData, FirebaseError, ReactivateSubjectVariables>): UseDataConnectMutationResult<ReactivateSubjectData, ReactivateSubjectVariables>;
export function useReactivateSubject(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateSubjectData, FirebaseError, ReactivateSubjectVariables>): UseDataConnectMutationResult<ReactivateSubjectData, ReactivateSubjectVariables>;

export function useCreateUnit(options?: useDataConnectMutationOptions<CreateUnitData, FirebaseError, CreateUnitVariables>): UseDataConnectMutationResult<CreateUnitData, CreateUnitVariables>;
export function useCreateUnit(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUnitData, FirebaseError, CreateUnitVariables>): UseDataConnectMutationResult<CreateUnitData, CreateUnitVariables>;

export function useUpdateUnit(options?: useDataConnectMutationOptions<UpdateUnitData, FirebaseError, UpdateUnitVariables>): UseDataConnectMutationResult<UpdateUnitData, UpdateUnitVariables>;
export function useUpdateUnit(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUnitData, FirebaseError, UpdateUnitVariables>): UseDataConnectMutationResult<UpdateUnitData, UpdateUnitVariables>;

export function useDeactivateUnit(options?: useDataConnectMutationOptions<DeactivateUnitData, FirebaseError, DeactivateUnitVariables>): UseDataConnectMutationResult<DeactivateUnitData, DeactivateUnitVariables>;
export function useDeactivateUnit(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateUnitData, FirebaseError, DeactivateUnitVariables>): UseDataConnectMutationResult<DeactivateUnitData, DeactivateUnitVariables>;

export function useReactivateUnit(options?: useDataConnectMutationOptions<ReactivateUnitData, FirebaseError, ReactivateUnitVariables>): UseDataConnectMutationResult<ReactivateUnitData, ReactivateUnitVariables>;
export function useReactivateUnit(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateUnitData, FirebaseError, ReactivateUnitVariables>): UseDataConnectMutationResult<ReactivateUnitData, ReactivateUnitVariables>;

export function useCreateTopic(options?: useDataConnectMutationOptions<CreateTopicData, FirebaseError, CreateTopicVariables>): UseDataConnectMutationResult<CreateTopicData, CreateTopicVariables>;
export function useCreateTopic(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTopicData, FirebaseError, CreateTopicVariables>): UseDataConnectMutationResult<CreateTopicData, CreateTopicVariables>;

export function useUpdateTopic(options?: useDataConnectMutationOptions<UpdateTopicData, FirebaseError, UpdateTopicVariables>): UseDataConnectMutationResult<UpdateTopicData, UpdateTopicVariables>;
export function useUpdateTopic(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTopicData, FirebaseError, UpdateTopicVariables>): UseDataConnectMutationResult<UpdateTopicData, UpdateTopicVariables>;

export function useDeactivateTopic(options?: useDataConnectMutationOptions<DeactivateTopicData, FirebaseError, DeactivateTopicVariables>): UseDataConnectMutationResult<DeactivateTopicData, DeactivateTopicVariables>;
export function useDeactivateTopic(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateTopicData, FirebaseError, DeactivateTopicVariables>): UseDataConnectMutationResult<DeactivateTopicData, DeactivateTopicVariables>;

export function useReactivateTopic(options?: useDataConnectMutationOptions<ReactivateTopicData, FirebaseError, ReactivateTopicVariables>): UseDataConnectMutationResult<ReactivateTopicData, ReactivateTopicVariables>;
export function useReactivateTopic(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateTopicData, FirebaseError, ReactivateTopicVariables>): UseDataConnectMutationResult<ReactivateTopicData, ReactivateTopicVariables>;

export function useCreateLevelCategory(options?: useDataConnectMutationOptions<CreateLevelCategoryData, FirebaseError, CreateLevelCategoryVariables>): UseDataConnectMutationResult<CreateLevelCategoryData, CreateLevelCategoryVariables>;
export function useCreateLevelCategory(dc: DataConnect, options?: useDataConnectMutationOptions<CreateLevelCategoryData, FirebaseError, CreateLevelCategoryVariables>): UseDataConnectMutationResult<CreateLevelCategoryData, CreateLevelCategoryVariables>;

export function useUpdateLevelCategory(options?: useDataConnectMutationOptions<UpdateLevelCategoryData, FirebaseError, UpdateLevelCategoryVariables>): UseDataConnectMutationResult<UpdateLevelCategoryData, UpdateLevelCategoryVariables>;
export function useUpdateLevelCategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateLevelCategoryData, FirebaseError, UpdateLevelCategoryVariables>): UseDataConnectMutationResult<UpdateLevelCategoryData, UpdateLevelCategoryVariables>;

export function useDeactivateLevelCategory(options?: useDataConnectMutationOptions<DeactivateLevelCategoryData, FirebaseError, DeactivateLevelCategoryVariables>): UseDataConnectMutationResult<DeactivateLevelCategoryData, DeactivateLevelCategoryVariables>;
export function useDeactivateLevelCategory(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateLevelCategoryData, FirebaseError, DeactivateLevelCategoryVariables>): UseDataConnectMutationResult<DeactivateLevelCategoryData, DeactivateLevelCategoryVariables>;

export function useReactivateLevelCategory(options?: useDataConnectMutationOptions<ReactivateLevelCategoryData, FirebaseError, ReactivateLevelCategoryVariables>): UseDataConnectMutationResult<ReactivateLevelCategoryData, ReactivateLevelCategoryVariables>;
export function useReactivateLevelCategory(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateLevelCategoryData, FirebaseError, ReactivateLevelCategoryVariables>): UseDataConnectMutationResult<ReactivateLevelCategoryData, ReactivateLevelCategoryVariables>;

export function useCreateEducationalLevel(options?: useDataConnectMutationOptions<CreateEducationalLevelData, FirebaseError, CreateEducationalLevelVariables>): UseDataConnectMutationResult<CreateEducationalLevelData, CreateEducationalLevelVariables>;
export function useCreateEducationalLevel(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEducationalLevelData, FirebaseError, CreateEducationalLevelVariables>): UseDataConnectMutationResult<CreateEducationalLevelData, CreateEducationalLevelVariables>;

export function useUpdateEducationalLevel(options?: useDataConnectMutationOptions<UpdateEducationalLevelData, FirebaseError, UpdateEducationalLevelVariables>): UseDataConnectMutationResult<UpdateEducationalLevelData, UpdateEducationalLevelVariables>;
export function useUpdateEducationalLevel(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEducationalLevelData, FirebaseError, UpdateEducationalLevelVariables>): UseDataConnectMutationResult<UpdateEducationalLevelData, UpdateEducationalLevelVariables>;

export function useDeactivateEducationalLevel(options?: useDataConnectMutationOptions<DeactivateEducationalLevelData, FirebaseError, DeactivateEducationalLevelVariables>): UseDataConnectMutationResult<DeactivateEducationalLevelData, DeactivateEducationalLevelVariables>;
export function useDeactivateEducationalLevel(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateEducationalLevelData, FirebaseError, DeactivateEducationalLevelVariables>): UseDataConnectMutationResult<DeactivateEducationalLevelData, DeactivateEducationalLevelVariables>;

export function useReactivateEducationalLevel(options?: useDataConnectMutationOptions<ReactivateEducationalLevelData, FirebaseError, ReactivateEducationalLevelVariables>): UseDataConnectMutationResult<ReactivateEducationalLevelData, ReactivateEducationalLevelVariables>;
export function useReactivateEducationalLevel(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateEducationalLevelData, FirebaseError, ReactivateEducationalLevelVariables>): UseDataConnectMutationResult<ReactivateEducationalLevelData, ReactivateEducationalLevelVariables>;

export function useCreateCourse(options?: useDataConnectMutationOptions<CreateCourseData, FirebaseError, CreateCourseVariables>): UseDataConnectMutationResult<CreateCourseData, CreateCourseVariables>;
export function useCreateCourse(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCourseData, FirebaseError, CreateCourseVariables>): UseDataConnectMutationResult<CreateCourseData, CreateCourseVariables>;

export function useUpdateCourse(options?: useDataConnectMutationOptions<UpdateCourseData, FirebaseError, UpdateCourseVariables>): UseDataConnectMutationResult<UpdateCourseData, UpdateCourseVariables>;
export function useUpdateCourse(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateCourseData, FirebaseError, UpdateCourseVariables>): UseDataConnectMutationResult<UpdateCourseData, UpdateCourseVariables>;

export function useDeactivateCourse(options?: useDataConnectMutationOptions<DeactivateCourseData, FirebaseError, DeactivateCourseVariables>): UseDataConnectMutationResult<DeactivateCourseData, DeactivateCourseVariables>;
export function useDeactivateCourse(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateCourseData, FirebaseError, DeactivateCourseVariables>): UseDataConnectMutationResult<DeactivateCourseData, DeactivateCourseVariables>;

export function useReactivateCourse(options?: useDataConnectMutationOptions<ReactivateCourseData, FirebaseError, ReactivateCourseVariables>): UseDataConnectMutationResult<ReactivateCourseData, ReactivateCourseVariables>;
export function useReactivateCourse(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateCourseData, FirebaseError, ReactivateCourseVariables>): UseDataConnectMutationResult<ReactivateCourseData, ReactivateCourseVariables>;

export function useCreateQuestion(options?: useDataConnectMutationOptions<CreateQuestionData, FirebaseError, CreateQuestionVariables>): UseDataConnectMutationResult<CreateQuestionData, CreateQuestionVariables>;
export function useCreateQuestion(dc: DataConnect, options?: useDataConnectMutationOptions<CreateQuestionData, FirebaseError, CreateQuestionVariables>): UseDataConnectMutationResult<CreateQuestionData, CreateQuestionVariables>;

export function useCreateQuestionVersion(options?: useDataConnectMutationOptions<CreateQuestionVersionData, FirebaseError, CreateQuestionVersionVariables>): UseDataConnectMutationResult<CreateQuestionVersionData, CreateQuestionVersionVariables>;
export function useCreateQuestionVersion(dc: DataConnect, options?: useDataConnectMutationOptions<CreateQuestionVersionData, FirebaseError, CreateQuestionVersionVariables>): UseDataConnectMutationResult<CreateQuestionVersionData, CreateQuestionVersionVariables>;

export function useUpdateQuestion(options?: useDataConnectMutationOptions<UpdateQuestionData, FirebaseError, UpdateQuestionVariables>): UseDataConnectMutationResult<UpdateQuestionData, UpdateQuestionVariables>;
export function useUpdateQuestion(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateQuestionData, FirebaseError, UpdateQuestionVariables>): UseDataConnectMutationResult<UpdateQuestionData, UpdateQuestionVariables>;

export function useDeactivateQuestion(options?: useDataConnectMutationOptions<DeactivateQuestionData, FirebaseError, DeactivateQuestionVariables>): UseDataConnectMutationResult<DeactivateQuestionData, DeactivateQuestionVariables>;
export function useDeactivateQuestion(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateQuestionData, FirebaseError, DeactivateQuestionVariables>): UseDataConnectMutationResult<DeactivateQuestionData, DeactivateQuestionVariables>;

export function useReactivateQuestion(options?: useDataConnectMutationOptions<ReactivateQuestionData, FirebaseError, ReactivateQuestionVariables>): UseDataConnectMutationResult<ReactivateQuestionData, ReactivateQuestionVariables>;
export function useReactivateQuestion(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateQuestionData, FirebaseError, ReactivateQuestionVariables>): UseDataConnectMutationResult<ReactivateQuestionData, ReactivateQuestionVariables>;

export function useCreateQuestionOption(options?: useDataConnectMutationOptions<CreateQuestionOptionData, FirebaseError, CreateQuestionOptionVariables>): UseDataConnectMutationResult<CreateQuestionOptionData, CreateQuestionOptionVariables>;
export function useCreateQuestionOption(dc: DataConnect, options?: useDataConnectMutationOptions<CreateQuestionOptionData, FirebaseError, CreateQuestionOptionVariables>): UseDataConnectMutationResult<CreateQuestionOptionData, CreateQuestionOptionVariables>;

export function useUpdateQuestionOption(options?: useDataConnectMutationOptions<UpdateQuestionOptionData, FirebaseError, UpdateQuestionOptionVariables>): UseDataConnectMutationResult<UpdateQuestionOptionData, UpdateQuestionOptionVariables>;
export function useUpdateQuestionOption(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateQuestionOptionData, FirebaseError, UpdateQuestionOptionVariables>): UseDataConnectMutationResult<UpdateQuestionOptionData, UpdateQuestionOptionVariables>;

export function useDeleteQuestionOption(options?: useDataConnectMutationOptions<DeleteQuestionOptionData, FirebaseError, DeleteQuestionOptionVariables>): UseDataConnectMutationResult<DeleteQuestionOptionData, DeleteQuestionOptionVariables>;
export function useDeleteQuestionOption(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteQuestionOptionData, FirebaseError, DeleteQuestionOptionVariables>): UseDataConnectMutationResult<DeleteQuestionOptionData, DeleteQuestionOptionVariables>;

export function useCreateQuestionType(options?: useDataConnectMutationOptions<CreateQuestionTypeData, FirebaseError, CreateQuestionTypeVariables>): UseDataConnectMutationResult<CreateQuestionTypeData, CreateQuestionTypeVariables>;
export function useCreateQuestionType(dc: DataConnect, options?: useDataConnectMutationOptions<CreateQuestionTypeData, FirebaseError, CreateQuestionTypeVariables>): UseDataConnectMutationResult<CreateQuestionTypeData, CreateQuestionTypeVariables>;

export function useUpdateQuestionType(options?: useDataConnectMutationOptions<UpdateQuestionTypeData, FirebaseError, UpdateQuestionTypeVariables>): UseDataConnectMutationResult<UpdateQuestionTypeData, UpdateQuestionTypeVariables>;
export function useUpdateQuestionType(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateQuestionTypeData, FirebaseError, UpdateQuestionTypeVariables>): UseDataConnectMutationResult<UpdateQuestionTypeData, UpdateQuestionTypeVariables>;

export function useDeactivateQuestionType(options?: useDataConnectMutationOptions<DeactivateQuestionTypeData, FirebaseError, DeactivateQuestionTypeVariables>): UseDataConnectMutationResult<DeactivateQuestionTypeData, DeactivateQuestionTypeVariables>;
export function useDeactivateQuestionType(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateQuestionTypeData, FirebaseError, DeactivateQuestionTypeVariables>): UseDataConnectMutationResult<DeactivateQuestionTypeData, DeactivateQuestionTypeVariables>;

export function useReactivateQuestionType(options?: useDataConnectMutationOptions<ReactivateQuestionTypeData, FirebaseError, ReactivateQuestionTypeVariables>): UseDataConnectMutationResult<ReactivateQuestionTypeData, ReactivateQuestionTypeVariables>;
export function useReactivateQuestionType(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateQuestionTypeData, FirebaseError, ReactivateQuestionTypeVariables>): UseDataConnectMutationResult<ReactivateQuestionTypeData, ReactivateQuestionTypeVariables>;

export function useCreateDifficulty(options?: useDataConnectMutationOptions<CreateDifficultyData, FirebaseError, CreateDifficultyVariables>): UseDataConnectMutationResult<CreateDifficultyData, CreateDifficultyVariables>;
export function useCreateDifficulty(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDifficultyData, FirebaseError, CreateDifficultyVariables>): UseDataConnectMutationResult<CreateDifficultyData, CreateDifficultyVariables>;

export function useDeactivateDifficulty(options?: useDataConnectMutationOptions<DeactivateDifficultyData, FirebaseError, DeactivateDifficultyVariables>): UseDataConnectMutationResult<DeactivateDifficultyData, DeactivateDifficultyVariables>;
export function useDeactivateDifficulty(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateDifficultyData, FirebaseError, DeactivateDifficultyVariables>): UseDataConnectMutationResult<DeactivateDifficultyData, DeactivateDifficultyVariables>;

export function useReactivateDifficulty(options?: useDataConnectMutationOptions<ReactivateDifficultyData, FirebaseError, ReactivateDifficultyVariables>): UseDataConnectMutationResult<ReactivateDifficultyData, ReactivateDifficultyVariables>;
export function useReactivateDifficulty(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateDifficultyData, FirebaseError, ReactivateDifficultyVariables>): UseDataConnectMutationResult<ReactivateDifficultyData, ReactivateDifficultyVariables>;

export function useCreateTaxonomy(options?: useDataConnectMutationOptions<CreateTaxonomyData, FirebaseError, CreateTaxonomyVariables>): UseDataConnectMutationResult<CreateTaxonomyData, CreateTaxonomyVariables>;
export function useCreateTaxonomy(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTaxonomyData, FirebaseError, CreateTaxonomyVariables>): UseDataConnectMutationResult<CreateTaxonomyData, CreateTaxonomyVariables>;

export function useUpdateTaxonomy(options?: useDataConnectMutationOptions<UpdateTaxonomyData, FirebaseError, UpdateTaxonomyVariables>): UseDataConnectMutationResult<UpdateTaxonomyData, UpdateTaxonomyVariables>;
export function useUpdateTaxonomy(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTaxonomyData, FirebaseError, UpdateTaxonomyVariables>): UseDataConnectMutationResult<UpdateTaxonomyData, UpdateTaxonomyVariables>;

export function useDeactivateTaxonomy(options?: useDataConnectMutationOptions<DeactivateTaxonomyData, FirebaseError, DeactivateTaxonomyVariables>): UseDataConnectMutationResult<DeactivateTaxonomyData, DeactivateTaxonomyVariables>;
export function useDeactivateTaxonomy(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateTaxonomyData, FirebaseError, DeactivateTaxonomyVariables>): UseDataConnectMutationResult<DeactivateTaxonomyData, DeactivateTaxonomyVariables>;

export function useReactivateTaxonomy(options?: useDataConnectMutationOptions<ReactivateTaxonomyData, FirebaseError, ReactivateTaxonomyVariables>): UseDataConnectMutationResult<ReactivateTaxonomyData, ReactivateTaxonomyVariables>;
export function useReactivateTaxonomy(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateTaxonomyData, FirebaseError, ReactivateTaxonomyVariables>): UseDataConnectMutationResult<ReactivateTaxonomyData, ReactivateTaxonomyVariables>;

export function useCreateEvaluation(options?: useDataConnectMutationOptions<CreateEvaluationData, FirebaseError, CreateEvaluationVariables>): UseDataConnectMutationResult<CreateEvaluationData, CreateEvaluationVariables>;
export function useCreateEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEvaluationData, FirebaseError, CreateEvaluationVariables>): UseDataConnectMutationResult<CreateEvaluationData, CreateEvaluationVariables>;

export function useUpdateEvaluation(options?: useDataConnectMutationOptions<UpdateEvaluationData, FirebaseError, UpdateEvaluationVariables>): UseDataConnectMutationResult<UpdateEvaluationData, UpdateEvaluationVariables>;
export function useUpdateEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEvaluationData, FirebaseError, UpdateEvaluationVariables>): UseDataConnectMutationResult<UpdateEvaluationData, UpdateEvaluationVariables>;

export function useUpdateEvaluationState(options?: useDataConnectMutationOptions<UpdateEvaluationStateData, FirebaseError, UpdateEvaluationStateVariables>): UseDataConnectMutationResult<UpdateEvaluationStateData, UpdateEvaluationStateVariables>;
export function useUpdateEvaluationState(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEvaluationStateData, FirebaseError, UpdateEvaluationStateVariables>): UseDataConnectMutationResult<UpdateEvaluationStateData, UpdateEvaluationStateVariables>;

export function useDeactivateEvaluation(options?: useDataConnectMutationOptions<DeactivateEvaluationData, FirebaseError, DeactivateEvaluationVariables>): UseDataConnectMutationResult<DeactivateEvaluationData, DeactivateEvaluationVariables>;
export function useDeactivateEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateEvaluationData, FirebaseError, DeactivateEvaluationVariables>): UseDataConnectMutationResult<DeactivateEvaluationData, DeactivateEvaluationVariables>;

export function useReactivateEvaluation(options?: useDataConnectMutationOptions<ReactivateEvaluationData, FirebaseError, ReactivateEvaluationVariables>): UseDataConnectMutationResult<ReactivateEvaluationData, ReactivateEvaluationVariables>;
export function useReactivateEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateEvaluationData, FirebaseError, ReactivateEvaluationVariables>): UseDataConnectMutationResult<ReactivateEvaluationData, ReactivateEvaluationVariables>;

export function useAddQuestionToEvaluation(options?: useDataConnectMutationOptions<AddQuestionToEvaluationData, FirebaseError, AddQuestionToEvaluationVariables>): UseDataConnectMutationResult<AddQuestionToEvaluationData, AddQuestionToEvaluationVariables>;
export function useAddQuestionToEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<AddQuestionToEvaluationData, FirebaseError, AddQuestionToEvaluationVariables>): UseDataConnectMutationResult<AddQuestionToEvaluationData, AddQuestionToEvaluationVariables>;

export function useUpdateEvaluationQuestion(options?: useDataConnectMutationOptions<UpdateEvaluationQuestionData, FirebaseError, UpdateEvaluationQuestionVariables>): UseDataConnectMutationResult<UpdateEvaluationQuestionData, UpdateEvaluationQuestionVariables>;
export function useUpdateEvaluationQuestion(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEvaluationQuestionData, FirebaseError, UpdateEvaluationQuestionVariables>): UseDataConnectMutationResult<UpdateEvaluationQuestionData, UpdateEvaluationQuestionVariables>;

export function useRemoveQuestionFromEvaluation(options?: useDataConnectMutationOptions<RemoveQuestionFromEvaluationData, FirebaseError, RemoveQuestionFromEvaluationVariables>): UseDataConnectMutationResult<RemoveQuestionFromEvaluationData, RemoveQuestionFromEvaluationVariables>;
export function useRemoveQuestionFromEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<RemoveQuestionFromEvaluationData, FirebaseError, RemoveQuestionFromEvaluationVariables>): UseDataConnectMutationResult<RemoveQuestionFromEvaluationData, RemoveQuestionFromEvaluationVariables>;

export function useAssignEvaluationToCourse(options?: useDataConnectMutationOptions<AssignEvaluationToCourseData, FirebaseError, AssignEvaluationToCourseVariables>): UseDataConnectMutationResult<AssignEvaluationToCourseData, AssignEvaluationToCourseVariables>;
export function useAssignEvaluationToCourse(dc: DataConnect, options?: useDataConnectMutationOptions<AssignEvaluationToCourseData, FirebaseError, AssignEvaluationToCourseVariables>): UseDataConnectMutationResult<AssignEvaluationToCourseData, AssignEvaluationToCourseVariables>;

export function useRemoveEvaluationFromCourse(options?: useDataConnectMutationOptions<RemoveEvaluationFromCourseData, FirebaseError, RemoveEvaluationFromCourseVariables>): UseDataConnectMutationResult<RemoveEvaluationFromCourseData, RemoveEvaluationFromCourseVariables>;
export function useRemoveEvaluationFromCourse(dc: DataConnect, options?: useDataConnectMutationOptions<RemoveEvaluationFromCourseData, FirebaseError, RemoveEvaluationFromCourseVariables>): UseDataConnectMutationResult<RemoveEvaluationFromCourseData, RemoveEvaluationFromCourseVariables>;

export function useCreateStudent(options?: useDataConnectMutationOptions<CreateStudentData, FirebaseError, CreateStudentVariables>): UseDataConnectMutationResult<CreateStudentData, CreateStudentVariables>;
export function useCreateStudent(dc: DataConnect, options?: useDataConnectMutationOptions<CreateStudentData, FirebaseError, CreateStudentVariables>): UseDataConnectMutationResult<CreateStudentData, CreateStudentVariables>;

export function useUpdateStudent(options?: useDataConnectMutationOptions<UpdateStudentData, FirebaseError, UpdateStudentVariables>): UseDataConnectMutationResult<UpdateStudentData, UpdateStudentVariables>;
export function useUpdateStudent(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStudentData, FirebaseError, UpdateStudentVariables>): UseDataConnectMutationResult<UpdateStudentData, UpdateStudentVariables>;

export function useDeactivateStudent(options?: useDataConnectMutationOptions<DeactivateStudentData, FirebaseError, DeactivateStudentVariables>): UseDataConnectMutationResult<DeactivateStudentData, DeactivateStudentVariables>;
export function useDeactivateStudent(dc: DataConnect, options?: useDataConnectMutationOptions<DeactivateStudentData, FirebaseError, DeactivateStudentVariables>): UseDataConnectMutationResult<DeactivateStudentData, DeactivateStudentVariables>;

export function useReactivateStudent(options?: useDataConnectMutationOptions<ReactivateStudentData, FirebaseError, ReactivateStudentVariables>): UseDataConnectMutationResult<ReactivateStudentData, ReactivateStudentVariables>;
export function useReactivateStudent(dc: DataConnect, options?: useDataConnectMutationOptions<ReactivateStudentData, FirebaseError, ReactivateStudentVariables>): UseDataConnectMutationResult<ReactivateStudentData, ReactivateStudentVariables>;

export function useEnrollStudentInCourse(options?: useDataConnectMutationOptions<EnrollStudentInCourseData, FirebaseError, EnrollStudentInCourseVariables>): UseDataConnectMutationResult<EnrollStudentInCourseData, EnrollStudentInCourseVariables>;
export function useEnrollStudentInCourse(dc: DataConnect, options?: useDataConnectMutationOptions<EnrollStudentInCourseData, FirebaseError, EnrollStudentInCourseVariables>): UseDataConnectMutationResult<EnrollStudentInCourseData, EnrollStudentInCourseVariables>;

export function useUpdateCourseStudent(options?: useDataConnectMutationOptions<UpdateCourseStudentData, FirebaseError, UpdateCourseStudentVariables>): UseDataConnectMutationResult<UpdateCourseStudentData, UpdateCourseStudentVariables>;
export function useUpdateCourseStudent(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateCourseStudentData, FirebaseError, UpdateCourseStudentVariables>): UseDataConnectMutationResult<UpdateCourseStudentData, UpdateCourseStudentVariables>;

export function useUnenrollStudentFromCourse(options?: useDataConnectMutationOptions<UnenrollStudentFromCourseData, FirebaseError, UnenrollStudentFromCourseVariables>): UseDataConnectMutationResult<UnenrollStudentFromCourseData, UnenrollStudentFromCourseVariables>;
export function useUnenrollStudentFromCourse(dc: DataConnect, options?: useDataConnectMutationOptions<UnenrollStudentFromCourseData, FirebaseError, UnenrollStudentFromCourseVariables>): UseDataConnectMutationResult<UnenrollStudentFromCourseData, UnenrollStudentFromCourseVariables>;

export function useReenrollStudentInCourse(options?: useDataConnectMutationOptions<ReenrollStudentInCourseData, FirebaseError, ReenrollStudentInCourseVariables>): UseDataConnectMutationResult<ReenrollStudentInCourseData, ReenrollStudentInCourseVariables>;
export function useReenrollStudentInCourse(dc: DataConnect, options?: useDataConnectMutationOptions<ReenrollStudentInCourseData, FirebaseError, ReenrollStudentInCourseVariables>): UseDataConnectMutationResult<ReenrollStudentInCourseData, ReenrollStudentInCourseVariables>;

export function useCreateStudentEvaluation(options?: useDataConnectMutationOptions<CreateStudentEvaluationData, FirebaseError, CreateStudentEvaluationVariables>): UseDataConnectMutationResult<CreateStudentEvaluationData, CreateStudentEvaluationVariables>;
export function useCreateStudentEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<CreateStudentEvaluationData, FirebaseError, CreateStudentEvaluationVariables>): UseDataConnectMutationResult<CreateStudentEvaluationData, CreateStudentEvaluationVariables>;

export function useUpdateStudentEvaluationState(options?: useDataConnectMutationOptions<UpdateStudentEvaluationStateData, FirebaseError, UpdateStudentEvaluationStateVariables>): UseDataConnectMutationResult<UpdateStudentEvaluationStateData, UpdateStudentEvaluationStateVariables>;
export function useUpdateStudentEvaluationState(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStudentEvaluationStateData, FirebaseError, UpdateStudentEvaluationStateVariables>): UseDataConnectMutationResult<UpdateStudentEvaluationStateData, UpdateStudentEvaluationStateVariables>;

export function useStartStudentEvaluation(options?: useDataConnectMutationOptions<StartStudentEvaluationData, FirebaseError, StartStudentEvaluationVariables>): UseDataConnectMutationResult<StartStudentEvaluationData, StartStudentEvaluationVariables>;
export function useStartStudentEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<StartStudentEvaluationData, FirebaseError, StartStudentEvaluationVariables>): UseDataConnectMutationResult<StartStudentEvaluationData, StartStudentEvaluationVariables>;

export function useCompleteStudentEvaluation(options?: useDataConnectMutationOptions<CompleteStudentEvaluationData, FirebaseError, CompleteStudentEvaluationVariables>): UseDataConnectMutationResult<CompleteStudentEvaluationData, CompleteStudentEvaluationVariables>;
export function useCompleteStudentEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<CompleteStudentEvaluationData, FirebaseError, CompleteStudentEvaluationVariables>): UseDataConnectMutationResult<CompleteStudentEvaluationData, CompleteStudentEvaluationVariables>;

export function useGradeStudentEvaluation(options?: useDataConnectMutationOptions<GradeStudentEvaluationData, FirebaseError, GradeStudentEvaluationVariables>): UseDataConnectMutationResult<GradeStudentEvaluationData, GradeStudentEvaluationVariables>;
export function useGradeStudentEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<GradeStudentEvaluationData, FirebaseError, GradeStudentEvaluationVariables>): UseDataConnectMutationResult<GradeStudentEvaluationData, GradeStudentEvaluationVariables>;

export function useUpdateStudentEvaluationScore(options?: useDataConnectMutationOptions<UpdateStudentEvaluationScoreData, FirebaseError, UpdateStudentEvaluationScoreVariables>): UseDataConnectMutationResult<UpdateStudentEvaluationScoreData, UpdateStudentEvaluationScoreVariables>;
export function useUpdateStudentEvaluationScore(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStudentEvaluationScoreData, FirebaseError, UpdateStudentEvaluationScoreVariables>): UseDataConnectMutationResult<UpdateStudentEvaluationScoreData, UpdateStudentEvaluationScoreVariables>;

export function useAddQuestionToStudentEvaluation(options?: useDataConnectMutationOptions<AddQuestionToStudentEvaluationData, FirebaseError, AddQuestionToStudentEvaluationVariables>): UseDataConnectMutationResult<AddQuestionToStudentEvaluationData, AddQuestionToStudentEvaluationVariables>;
export function useAddQuestionToStudentEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<AddQuestionToStudentEvaluationData, FirebaseError, AddQuestionToStudentEvaluationVariables>): UseDataConnectMutationResult<AddQuestionToStudentEvaluationData, AddQuestionToStudentEvaluationVariables>;

export function useGradeStudentQuestion(options?: useDataConnectMutationOptions<GradeStudentQuestionData, FirebaseError, GradeStudentQuestionVariables>): UseDataConnectMutationResult<GradeStudentQuestionData, GradeStudentQuestionVariables>;
export function useGradeStudentQuestion(dc: DataConnect, options?: useDataConnectMutationOptions<GradeStudentQuestionData, FirebaseError, GradeStudentQuestionVariables>): UseDataConnectMutationResult<GradeStudentQuestionData, GradeStudentQuestionVariables>;

export function useUpdateStudentQuestionPosition(options?: useDataConnectMutationOptions<UpdateStudentQuestionPositionData, FirebaseError, UpdateStudentQuestionPositionVariables>): UseDataConnectMutationResult<UpdateStudentQuestionPositionData, UpdateStudentQuestionPositionVariables>;
export function useUpdateStudentQuestionPosition(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStudentQuestionPositionData, FirebaseError, UpdateStudentQuestionPositionVariables>): UseDataConnectMutationResult<UpdateStudentQuestionPositionData, UpdateStudentQuestionPositionVariables>;

export function useRemoveQuestionFromStudentEvaluation(options?: useDataConnectMutationOptions<RemoveQuestionFromStudentEvaluationData, FirebaseError, RemoveQuestionFromStudentEvaluationVariables>): UseDataConnectMutationResult<RemoveQuestionFromStudentEvaluationData, RemoveQuestionFromStudentEvaluationVariables>;
export function useRemoveQuestionFromStudentEvaluation(dc: DataConnect, options?: useDataConnectMutationOptions<RemoveQuestionFromStudentEvaluationData, FirebaseError, RemoveQuestionFromStudentEvaluationVariables>): UseDataConnectMutationResult<RemoveQuestionFromStudentEvaluationData, RemoveQuestionFromStudentEvaluationVariables>;

export function useRegisterStudentAnswer(options?: useDataConnectMutationOptions<RegisterStudentAnswerData, FirebaseError, RegisterStudentAnswerVariables>): UseDataConnectMutationResult<RegisterStudentAnswerData, RegisterStudentAnswerVariables>;
export function useRegisterStudentAnswer(dc: DataConnect, options?: useDataConnectMutationOptions<RegisterStudentAnswerData, FirebaseError, RegisterStudentAnswerVariables>): UseDataConnectMutationResult<RegisterStudentAnswerData, RegisterStudentAnswerVariables>;

export function useRemoveStudentAnswer(options?: useDataConnectMutationOptions<RemoveStudentAnswerData, FirebaseError, RemoveStudentAnswerVariables>): UseDataConnectMutationResult<RemoveStudentAnswerData, RemoveStudentAnswerVariables>;
export function useRemoveStudentAnswer(dc: DataConnect, options?: useDataConnectMutationOptions<RemoveStudentAnswerData, FirebaseError, RemoveStudentAnswerVariables>): UseDataConnectMutationResult<RemoveStudentAnswerData, RemoveStudentAnswerVariables>;

export function useGetUserByEmail(vars: GetUserByEmailVariables, options?: useDataConnectQueryOptions<GetUserByEmailData>): UseDataConnectQueryResult<GetUserByEmailData, GetUserByEmailVariables>;
export function useGetUserByEmail(dc: DataConnect, vars: GetUserByEmailVariables, options?: useDataConnectQueryOptions<GetUserByEmailData>): UseDataConnectQueryResult<GetUserByEmailData, GetUserByEmailVariables>;

export function useGetUserById(vars: GetUserByIdVariables, options?: useDataConnectQueryOptions<GetUserByIdData>): UseDataConnectQueryResult<GetUserByIdData, GetUserByIdVariables>;
export function useGetUserById(dc: DataConnect, vars: GetUserByIdVariables, options?: useDataConnectQueryOptions<GetUserByIdData>): UseDataConnectQueryResult<GetUserByIdData, GetUserByIdVariables>;

export function useListSubjects(options?: useDataConnectQueryOptions<ListSubjectsData>): UseDataConnectQueryResult<ListSubjectsData, undefined>;
export function useListSubjects(dc: DataConnect, options?: useDataConnectQueryOptions<ListSubjectsData>): UseDataConnectQueryResult<ListSubjectsData, undefined>;

export function useGetSubject(vars: GetSubjectVariables, options?: useDataConnectQueryOptions<GetSubjectData>): UseDataConnectQueryResult<GetSubjectData, GetSubjectVariables>;
export function useGetSubject(dc: DataConnect, vars: GetSubjectVariables, options?: useDataConnectQueryOptions<GetSubjectData>): UseDataConnectQueryResult<GetSubjectData, GetSubjectVariables>;

export function useListUnits(options?: useDataConnectQueryOptions<ListUnitsData>): UseDataConnectQueryResult<ListUnitsData, undefined>;
export function useListUnits(dc: DataConnect, options?: useDataConnectQueryOptions<ListUnitsData>): UseDataConnectQueryResult<ListUnitsData, undefined>;

export function useGetUnit(vars: GetUnitVariables, options?: useDataConnectQueryOptions<GetUnitData>): UseDataConnectQueryResult<GetUnitData, GetUnitVariables>;
export function useGetUnit(dc: DataConnect, vars: GetUnitVariables, options?: useDataConnectQueryOptions<GetUnitData>): UseDataConnectQueryResult<GetUnitData, GetUnitVariables>;

export function useListTopics(options?: useDataConnectQueryOptions<ListTopicsData>): UseDataConnectQueryResult<ListTopicsData, undefined>;
export function useListTopics(dc: DataConnect, options?: useDataConnectQueryOptions<ListTopicsData>): UseDataConnectQueryResult<ListTopicsData, undefined>;

export function useGetTopic(vars: GetTopicVariables, options?: useDataConnectQueryOptions<GetTopicData>): UseDataConnectQueryResult<GetTopicData, GetTopicVariables>;
export function useGetTopic(dc: DataConnect, vars: GetTopicVariables, options?: useDataConnectQueryOptions<GetTopicData>): UseDataConnectQueryResult<GetTopicData, GetTopicVariables>;

export function useListLevelCategories(options?: useDataConnectQueryOptions<ListLevelCategoriesData>): UseDataConnectQueryResult<ListLevelCategoriesData, undefined>;
export function useListLevelCategories(dc: DataConnect, options?: useDataConnectQueryOptions<ListLevelCategoriesData>): UseDataConnectQueryResult<ListLevelCategoriesData, undefined>;

export function useGetLevelCategory(vars: GetLevelCategoryVariables, options?: useDataConnectQueryOptions<GetLevelCategoryData>): UseDataConnectQueryResult<GetLevelCategoryData, GetLevelCategoryVariables>;
export function useGetLevelCategory(dc: DataConnect, vars: GetLevelCategoryVariables, options?: useDataConnectQueryOptions<GetLevelCategoryData>): UseDataConnectQueryResult<GetLevelCategoryData, GetLevelCategoryVariables>;

export function useListEducationalLevels(options?: useDataConnectQueryOptions<ListEducationalLevelsData>): UseDataConnectQueryResult<ListEducationalLevelsData, undefined>;
export function useListEducationalLevels(dc: DataConnect, options?: useDataConnectQueryOptions<ListEducationalLevelsData>): UseDataConnectQueryResult<ListEducationalLevelsData, undefined>;

export function useGetEducationalLevel(vars: GetEducationalLevelVariables, options?: useDataConnectQueryOptions<GetEducationalLevelData>): UseDataConnectQueryResult<GetEducationalLevelData, GetEducationalLevelVariables>;
export function useGetEducationalLevel(dc: DataConnect, vars: GetEducationalLevelVariables, options?: useDataConnectQueryOptions<GetEducationalLevelData>): UseDataConnectQueryResult<GetEducationalLevelData, GetEducationalLevelVariables>;

export function useGetLevelsByCategory(vars: GetLevelsByCategoryVariables, options?: useDataConnectQueryOptions<GetLevelsByCategoryData>): UseDataConnectQueryResult<GetLevelsByCategoryData, GetLevelsByCategoryVariables>;
export function useGetLevelsByCategory(dc: DataConnect, vars: GetLevelsByCategoryVariables, options?: useDataConnectQueryOptions<GetLevelsByCategoryData>): UseDataConnectQueryResult<GetLevelsByCategoryData, GetLevelsByCategoryVariables>;

export function useListCourses(vars: ListCoursesVariables, options?: useDataConnectQueryOptions<ListCoursesData>): UseDataConnectQueryResult<ListCoursesData, ListCoursesVariables>;
export function useListCourses(dc: DataConnect, vars: ListCoursesVariables, options?: useDataConnectQueryOptions<ListCoursesData>): UseDataConnectQueryResult<ListCoursesData, ListCoursesVariables>;

export function useGetCourse(vars: GetCourseVariables, options?: useDataConnectQueryOptions<GetCourseData>): UseDataConnectQueryResult<GetCourseData, GetCourseVariables>;
export function useGetCourse(dc: DataConnect, vars: GetCourseVariables, options?: useDataConnectQueryOptions<GetCourseData>): UseDataConnectQueryResult<GetCourseData, GetCourseVariables>;

export function useGetCoursesByUser(vars: GetCoursesByUserVariables, options?: useDataConnectQueryOptions<GetCoursesByUserData>): UseDataConnectQueryResult<GetCoursesByUserData, GetCoursesByUserVariables>;
export function useGetCoursesByUser(dc: DataConnect, vars: GetCoursesByUserVariables, options?: useDataConnectQueryOptions<GetCoursesByUserData>): UseDataConnectQueryResult<GetCoursesByUserData, GetCoursesByUserVariables>;

export function useGetCoursesByLevel(vars: GetCoursesByLevelVariables, options?: useDataConnectQueryOptions<GetCoursesByLevelData>): UseDataConnectQueryResult<GetCoursesByLevelData, GetCoursesByLevelVariables>;
export function useGetCoursesByLevel(dc: DataConnect, vars: GetCoursesByLevelVariables, options?: useDataConnectQueryOptions<GetCoursesByLevelData>): UseDataConnectQueryResult<GetCoursesByLevelData, GetCoursesByLevelVariables>;

export function useListDifficulties(options?: useDataConnectQueryOptions<ListDifficultiesData>): UseDataConnectQueryResult<ListDifficultiesData, undefined>;
export function useListDifficulties(dc: DataConnect, options?: useDataConnectQueryOptions<ListDifficultiesData>): UseDataConnectQueryResult<ListDifficultiesData, undefined>;

export function useGetDifficulty(vars: GetDifficultyVariables, options?: useDataConnectQueryOptions<GetDifficultyData>): UseDataConnectQueryResult<GetDifficultyData, GetDifficultyVariables>;
export function useGetDifficulty(dc: DataConnect, vars: GetDifficultyVariables, options?: useDataConnectQueryOptions<GetDifficultyData>): UseDataConnectQueryResult<GetDifficultyData, GetDifficultyVariables>;

export function useListQuestionTypes(options?: useDataConnectQueryOptions<ListQuestionTypesData>): UseDataConnectQueryResult<ListQuestionTypesData, undefined>;
export function useListQuestionTypes(dc: DataConnect, options?: useDataConnectQueryOptions<ListQuestionTypesData>): UseDataConnectQueryResult<ListQuestionTypesData, undefined>;

export function useGetQuestionType(vars: GetQuestionTypeVariables, options?: useDataConnectQueryOptions<GetQuestionTypeData>): UseDataConnectQueryResult<GetQuestionTypeData, GetQuestionTypeVariables>;
export function useGetQuestionType(dc: DataConnect, vars: GetQuestionTypeVariables, options?: useDataConnectQueryOptions<GetQuestionTypeData>): UseDataConnectQueryResult<GetQuestionTypeData, GetQuestionTypeVariables>;

export function useGetQuestionTypeByCode(vars: GetQuestionTypeByCodeVariables, options?: useDataConnectQueryOptions<GetQuestionTypeByCodeData>): UseDataConnectQueryResult<GetQuestionTypeByCodeData, GetQuestionTypeByCodeVariables>;
export function useGetQuestionTypeByCode(dc: DataConnect, vars: GetQuestionTypeByCodeVariables, options?: useDataConnectQueryOptions<GetQuestionTypeByCodeData>): UseDataConnectQueryResult<GetQuestionTypeByCodeData, GetQuestionTypeByCodeVariables>;

export function useListTaxonomies(options?: useDataConnectQueryOptions<ListTaxonomiesData>): UseDataConnectQueryResult<ListTaxonomiesData, undefined>;
export function useListTaxonomies(dc: DataConnect, options?: useDataConnectQueryOptions<ListTaxonomiesData>): UseDataConnectQueryResult<ListTaxonomiesData, undefined>;

export function useGetTaxonomy(vars: GetTaxonomyVariables, options?: useDataConnectQueryOptions<GetTaxonomyData>): UseDataConnectQueryResult<GetTaxonomyData, GetTaxonomyVariables>;
export function useGetTaxonomy(dc: DataConnect, vars: GetTaxonomyVariables, options?: useDataConnectQueryOptions<GetTaxonomyData>): UseDataConnectQueryResult<GetTaxonomyData, GetTaxonomyVariables>;

export function useGetTaxonomyByCode(vars: GetTaxonomyByCodeVariables, options?: useDataConnectQueryOptions<GetTaxonomyByCodeData>): UseDataConnectQueryResult<GetTaxonomyByCodeData, GetTaxonomyByCodeVariables>;
export function useGetTaxonomyByCode(dc: DataConnect, vars: GetTaxonomyByCodeVariables, options?: useDataConnectQueryOptions<GetTaxonomyByCodeData>): UseDataConnectQueryResult<GetTaxonomyByCodeData, GetTaxonomyByCodeVariables>;

export function useListTaxonomiesByLevel(options?: useDataConnectQueryOptions<ListTaxonomiesByLevelData>): UseDataConnectQueryResult<ListTaxonomiesByLevelData, undefined>;
export function useListTaxonomiesByLevel(dc: DataConnect, options?: useDataConnectQueryOptions<ListTaxonomiesByLevelData>): UseDataConnectQueryResult<ListTaxonomiesByLevelData, undefined>;

export function useListQuestionsByUser(vars: ListQuestionsByUserVariables, options?: useDataConnectQueryOptions<ListQuestionsByUserData>): UseDataConnectQueryResult<ListQuestionsByUserData, ListQuestionsByUserVariables>;
export function useListQuestionsByUser(dc: DataConnect, vars: ListQuestionsByUserVariables, options?: useDataConnectQueryOptions<ListQuestionsByUserData>): UseDataConnectQueryResult<ListQuestionsByUserData, ListQuestionsByUserVariables>;

export function useGetDashboardQuestions(vars: GetDashboardQuestionsVariables, options?: useDataConnectQueryOptions<GetDashboardQuestionsData>): UseDataConnectQueryResult<GetDashboardQuestionsData, GetDashboardQuestionsVariables>;
export function useGetDashboardQuestions(dc: DataConnect, vars: GetDashboardQuestionsVariables, options?: useDataConnectQueryOptions<GetDashboardQuestionsData>): UseDataConnectQueryResult<GetDashboardQuestionsData, GetDashboardQuestionsVariables>;

export function useGetDashboardSystemData(options?: useDataConnectQueryOptions<GetDashboardSystemDataData>): UseDataConnectQueryResult<GetDashboardSystemDataData, undefined>;
export function useGetDashboardSystemData(dc: DataConnect, options?: useDataConnectQueryOptions<GetDashboardSystemDataData>): UseDataConnectQueryResult<GetDashboardSystemDataData, undefined>;

export function useGetQuestion(vars: GetQuestionVariables, options?: useDataConnectQueryOptions<GetQuestionData>): UseDataConnectQueryResult<GetQuestionData, GetQuestionVariables>;
export function useGetQuestion(dc: DataConnect, vars: GetQuestionVariables, options?: useDataConnectQueryOptions<GetQuestionData>): UseDataConnectQueryResult<GetQuestionData, GetQuestionVariables>;

export function useListPublicQuestions(options?: useDataConnectQueryOptions<ListPublicQuestionsData>): UseDataConnectQueryResult<ListPublicQuestionsData, undefined>;
export function useListPublicQuestions(dc: DataConnect, options?: useDataConnectQueryOptions<ListPublicQuestionsData>): UseDataConnectQueryResult<ListPublicQuestionsData, undefined>;

export function useListPublicQuestionsByDifficulty(vars: ListPublicQuestionsByDifficultyVariables, options?: useDataConnectQueryOptions<ListPublicQuestionsByDifficultyData>): UseDataConnectQueryResult<ListPublicQuestionsByDifficultyData, ListPublicQuestionsByDifficultyVariables>;
export function useListPublicQuestionsByDifficulty(dc: DataConnect, vars: ListPublicQuestionsByDifficultyVariables, options?: useDataConnectQueryOptions<ListPublicQuestionsByDifficultyData>): UseDataConnectQueryResult<ListPublicQuestionsByDifficultyData, ListPublicQuestionsByDifficultyVariables>;

export function useListPublicQuestionsByType(vars: ListPublicQuestionsByTypeVariables, options?: useDataConnectQueryOptions<ListPublicQuestionsByTypeData>): UseDataConnectQueryResult<ListPublicQuestionsByTypeData, ListPublicQuestionsByTypeVariables>;
export function useListPublicQuestionsByType(dc: DataConnect, vars: ListPublicQuestionsByTypeVariables, options?: useDataConnectQueryOptions<ListPublicQuestionsByTypeData>): UseDataConnectQueryResult<ListPublicQuestionsByTypeData, ListPublicQuestionsByTypeVariables>;

export function useGetQuestionOptions(vars: GetQuestionOptionsVariables, options?: useDataConnectQueryOptions<GetQuestionOptionsData>): UseDataConnectQueryResult<GetQuestionOptionsData, GetQuestionOptionsVariables>;
export function useGetQuestionOptions(dc: DataConnect, vars: GetQuestionOptionsVariables, options?: useDataConnectQueryOptions<GetQuestionOptionsData>): UseDataConnectQueryResult<GetQuestionOptionsData, GetQuestionOptionsVariables>;

export function useGetAllCoursesByUser(vars: GetAllCoursesByUserVariables, options?: useDataConnectQueryOptions<GetAllCoursesByUserData>): UseDataConnectQueryResult<GetAllCoursesByUserData, GetAllCoursesByUserVariables>;
export function useGetAllCoursesByUser(dc: DataConnect, vars: GetAllCoursesByUserVariables, options?: useDataConnectQueryOptions<GetAllCoursesByUserData>): UseDataConnectQueryResult<GetAllCoursesByUserData, GetAllCoursesByUserVariables>;

export function useGetCourseByCode(vars: GetCourseByCodeVariables, options?: useDataConnectQueryOptions<GetCourseByCodeData>): UseDataConnectQueryResult<GetCourseByCodeData, GetCourseByCodeVariables>;
export function useGetCourseByCode(dc: DataConnect, vars: GetCourseByCodeVariables, options?: useDataConnectQueryOptions<GetCourseByCodeData>): UseDataConnectQueryResult<GetCourseByCodeData, GetCourseByCodeVariables>;

export function useGetCoursesByInstitution(vars: GetCoursesByInstitutionVariables, options?: useDataConnectQueryOptions<GetCoursesByInstitutionData>): UseDataConnectQueryResult<GetCoursesByInstitutionData, GetCoursesByInstitutionVariables>;
export function useGetCoursesByInstitution(dc: DataConnect, vars: GetCoursesByInstitutionVariables, options?: useDataConnectQueryOptions<GetCoursesByInstitutionData>): UseDataConnectQueryResult<GetCoursesByInstitutionData, GetCoursesByInstitutionVariables>;

export function useGetCoursesByEducationalLevel(vars: GetCoursesByEducationalLevelVariables, options?: useDataConnectQueryOptions<GetCoursesByEducationalLevelData>): UseDataConnectQueryResult<GetCoursesByEducationalLevelData, GetCoursesByEducationalLevelVariables>;
export function useGetCoursesByEducationalLevel(dc: DataConnect, vars: GetCoursesByEducationalLevelVariables, options?: useDataConnectQueryOptions<GetCoursesByEducationalLevelData>): UseDataConnectQueryResult<GetCoursesByEducationalLevelData, GetCoursesByEducationalLevelVariables>;

export function useGetEvaluationById(vars: GetEvaluationByIdVariables, options?: useDataConnectQueryOptions<GetEvaluationByIdData>): UseDataConnectQueryResult<GetEvaluationByIdData, GetEvaluationByIdVariables>;
export function useGetEvaluationById(dc: DataConnect, vars: GetEvaluationByIdVariables, options?: useDataConnectQueryOptions<GetEvaluationByIdData>): UseDataConnectQueryResult<GetEvaluationByIdData, GetEvaluationByIdVariables>;

export function useGetAllEvaluationsByUser(vars: GetAllEvaluationsByUserVariables, options?: useDataConnectQueryOptions<GetAllEvaluationsByUserData>): UseDataConnectQueryResult<GetAllEvaluationsByUserData, GetAllEvaluationsByUserVariables>;
export function useGetAllEvaluationsByUser(dc: DataConnect, vars: GetAllEvaluationsByUserVariables, options?: useDataConnectQueryOptions<GetAllEvaluationsByUserData>): UseDataConnectQueryResult<GetAllEvaluationsByUserData, GetAllEvaluationsByUserVariables>;

export function useGetEvaluationsByDateRange(vars: GetEvaluationsByDateRangeVariables, options?: useDataConnectQueryOptions<GetEvaluationsByDateRangeData>): UseDataConnectQueryResult<GetEvaluationsByDateRangeData, GetEvaluationsByDateRangeVariables>;
export function useGetEvaluationsByDateRange(dc: DataConnect, vars: GetEvaluationsByDateRangeVariables, options?: useDataConnectQueryOptions<GetEvaluationsByDateRangeData>): UseDataConnectQueryResult<GetEvaluationsByDateRangeData, GetEvaluationsByDateRangeVariables>;

export function useGetEvaluationsByState(vars: GetEvaluationsByStateVariables, options?: useDataConnectQueryOptions<GetEvaluationsByStateData>): UseDataConnectQueryResult<GetEvaluationsByStateData, GetEvaluationsByStateVariables>;
export function useGetEvaluationsByState(dc: DataConnect, vars: GetEvaluationsByStateVariables, options?: useDataConnectQueryOptions<GetEvaluationsByStateData>): UseDataConnectQueryResult<GetEvaluationsByStateData, GetEvaluationsByStateVariables>;

export function useGetEvaluationsBySubject(vars: GetEvaluationsBySubjectVariables, options?: useDataConnectQueryOptions<GetEvaluationsBySubjectData>): UseDataConnectQueryResult<GetEvaluationsBySubjectData, GetEvaluationsBySubjectVariables>;
export function useGetEvaluationsBySubject(dc: DataConnect, vars: GetEvaluationsBySubjectVariables, options?: useDataConnectQueryOptions<GetEvaluationsBySubjectData>): UseDataConnectQueryResult<GetEvaluationsBySubjectData, GetEvaluationsBySubjectVariables>;

export function useGetEvaluationsByCourse(vars: GetEvaluationsByCourseVariables, options?: useDataConnectQueryOptions<GetEvaluationsByCourseData>): UseDataConnectQueryResult<GetEvaluationsByCourseData, GetEvaluationsByCourseVariables>;
export function useGetEvaluationsByCourse(dc: DataConnect, vars: GetEvaluationsByCourseVariables, options?: useDataConnectQueryOptions<GetEvaluationsByCourseData>): UseDataConnectQueryResult<GetEvaluationsByCourseData, GetEvaluationsByCourseVariables>;

export function useGetEvaluationFullDetail(vars: GetEvaluationFullDetailVariables, options?: useDataConnectQueryOptions<GetEvaluationFullDetailData>): UseDataConnectQueryResult<GetEvaluationFullDetailData, GetEvaluationFullDetailVariables>;
export function useGetEvaluationFullDetail(dc: DataConnect, vars: GetEvaluationFullDetailVariables, options?: useDataConnectQueryOptions<GetEvaluationFullDetailData>): UseDataConnectQueryResult<GetEvaluationFullDetailData, GetEvaluationFullDetailVariables>;

export function useGetEvaluationQuestions(vars: GetEvaluationQuestionsVariables, options?: useDataConnectQueryOptions<GetEvaluationQuestionsData>): UseDataConnectQueryResult<GetEvaluationQuestionsData, GetEvaluationQuestionsVariables>;
export function useGetEvaluationQuestions(dc: DataConnect, vars: GetEvaluationQuestionsVariables, options?: useDataConnectQueryOptions<GetEvaluationQuestionsData>): UseDataConnectQueryResult<GetEvaluationQuestionsData, GetEvaluationQuestionsVariables>;

export function useGetAllStudentsByUser(vars: GetAllStudentsByUserVariables, options?: useDataConnectQueryOptions<GetAllStudentsByUserData>): UseDataConnectQueryResult<GetAllStudentsByUserData, GetAllStudentsByUserVariables>;
export function useGetAllStudentsByUser(dc: DataConnect, vars: GetAllStudentsByUserVariables, options?: useDataConnectQueryOptions<GetAllStudentsByUserData>): UseDataConnectQueryResult<GetAllStudentsByUserData, GetAllStudentsByUserVariables>;

export function useGetStudentById(vars: GetStudentByIdVariables, options?: useDataConnectQueryOptions<GetStudentByIdData>): UseDataConnectQueryResult<GetStudentByIdData, GetStudentByIdVariables>;
export function useGetStudentById(dc: DataConnect, vars: GetStudentByIdVariables, options?: useDataConnectQueryOptions<GetStudentByIdData>): UseDataConnectQueryResult<GetStudentByIdData, GetStudentByIdVariables>;

export function useGetStudentByIdentifier(vars: GetStudentByIdentifierVariables, options?: useDataConnectQueryOptions<GetStudentByIdentifierData>): UseDataConnectQueryResult<GetStudentByIdentifierData, GetStudentByIdentifierVariables>;
export function useGetStudentByIdentifier(dc: DataConnect, vars: GetStudentByIdentifierVariables, options?: useDataConnectQueryOptions<GetStudentByIdentifierData>): UseDataConnectQueryResult<GetStudentByIdentifierData, GetStudentByIdentifierVariables>;

export function useGetStudentsByFirstName(vars: GetStudentsByFirstNameVariables, options?: useDataConnectQueryOptions<GetStudentsByFirstNameData>): UseDataConnectQueryResult<GetStudentsByFirstNameData, GetStudentsByFirstNameVariables>;
export function useGetStudentsByFirstName(dc: DataConnect, vars: GetStudentsByFirstNameVariables, options?: useDataConnectQueryOptions<GetStudentsByFirstNameData>): UseDataConnectQueryResult<GetStudentsByFirstNameData, GetStudentsByFirstNameVariables>;

export function useGetStudentsByLastName(vars: GetStudentsByLastNameVariables, options?: useDataConnectQueryOptions<GetStudentsByLastNameData>): UseDataConnectQueryResult<GetStudentsByLastNameData, GetStudentsByLastNameVariables>;
export function useGetStudentsByLastName(dc: DataConnect, vars: GetStudentsByLastNameVariables, options?: useDataConnectQueryOptions<GetStudentsByLastNameData>): UseDataConnectQueryResult<GetStudentsByLastNameData, GetStudentsByLastNameVariables>;

export function useGetStudentsByCourse(vars: GetStudentsByCourseVariables, options?: useDataConnectQueryOptions<GetStudentsByCourseData>): UseDataConnectQueryResult<GetStudentsByCourseData, GetStudentsByCourseVariables>;
export function useGetStudentsByCourse(dc: DataConnect, vars: GetStudentsByCourseVariables, options?: useDataConnectQueryOptions<GetStudentsByCourseData>): UseDataConnectQueryResult<GetStudentsByCourseData, GetStudentsByCourseVariables>;

export function useGetCourseStudentsDetail(vars: GetCourseStudentsDetailVariables, options?: useDataConnectQueryOptions<GetCourseStudentsDetailData>): UseDataConnectQueryResult<GetCourseStudentsDetailData, GetCourseStudentsDetailVariables>;
export function useGetCourseStudentsDetail(dc: DataConnect, vars: GetCourseStudentsDetailVariables, options?: useDataConnectQueryOptions<GetCourseStudentsDetailData>): UseDataConnectQueryResult<GetCourseStudentsDetailData, GetCourseStudentsDetailVariables>;

export function useGetCourseStudentsWithDetails(vars: GetCourseStudentsWithDetailsVariables, options?: useDataConnectQueryOptions<GetCourseStudentsWithDetailsData>): UseDataConnectQueryResult<GetCourseStudentsWithDetailsData, GetCourseStudentsWithDetailsVariables>;
export function useGetCourseStudentsWithDetails(dc: DataConnect, vars: GetCourseStudentsWithDetailsVariables, options?: useDataConnectQueryOptions<GetCourseStudentsWithDetailsData>): UseDataConnectQueryResult<GetCourseStudentsWithDetailsData, GetCourseStudentsWithDetailsVariables>;

export function useGetStudentEvaluationById(vars: GetStudentEvaluationByIdVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationByIdData>): UseDataConnectQueryResult<GetStudentEvaluationByIdData, GetStudentEvaluationByIdVariables>;
export function useGetStudentEvaluationById(dc: DataConnect, vars: GetStudentEvaluationByIdVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationByIdData>): UseDataConnectQueryResult<GetStudentEvaluationByIdData, GetStudentEvaluationByIdVariables>;

export function useGetStudentEvaluationsByStudentId(vars: GetStudentEvaluationsByStudentIdVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByStudentIdData>): UseDataConnectQueryResult<GetStudentEvaluationsByStudentIdData, GetStudentEvaluationsByStudentIdVariables>;
export function useGetStudentEvaluationsByStudentId(dc: DataConnect, vars: GetStudentEvaluationsByStudentIdVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByStudentIdData>): UseDataConnectQueryResult<GetStudentEvaluationsByStudentIdData, GetStudentEvaluationsByStudentIdVariables>;

export function useGetStudentEvaluationsByIdentifier(vars: GetStudentEvaluationsByIdentifierVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByIdentifierData>): UseDataConnectQueryResult<GetStudentEvaluationsByIdentifierData, GetStudentEvaluationsByIdentifierVariables>;
export function useGetStudentEvaluationsByIdentifier(dc: DataConnect, vars: GetStudentEvaluationsByIdentifierVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByIdentifierData>): UseDataConnectQueryResult<GetStudentEvaluationsByIdentifierData, GetStudentEvaluationsByIdentifierVariables>;

export function useGetStudentEvaluationsByFirstName(vars: GetStudentEvaluationsByFirstNameVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByFirstNameData>): UseDataConnectQueryResult<GetStudentEvaluationsByFirstNameData, GetStudentEvaluationsByFirstNameVariables>;
export function useGetStudentEvaluationsByFirstName(dc: DataConnect, vars: GetStudentEvaluationsByFirstNameVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByFirstNameData>): UseDataConnectQueryResult<GetStudentEvaluationsByFirstNameData, GetStudentEvaluationsByFirstNameVariables>;

export function useGetStudentEvaluationsByLastName(vars: GetStudentEvaluationsByLastNameVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByLastNameData>): UseDataConnectQueryResult<GetStudentEvaluationsByLastNameData, GetStudentEvaluationsByLastNameVariables>;
export function useGetStudentEvaluationsByLastName(dc: DataConnect, vars: GetStudentEvaluationsByLastNameVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByLastNameData>): UseDataConnectQueryResult<GetStudentEvaluationsByLastNameData, GetStudentEvaluationsByLastNameVariables>;

export function useGetStudentEvaluationQuestions(vars: GetStudentEvaluationQuestionsVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationQuestionsData>): UseDataConnectQueryResult<GetStudentEvaluationQuestionsData, GetStudentEvaluationQuestionsVariables>;
export function useGetStudentEvaluationQuestions(dc: DataConnect, vars: GetStudentEvaluationQuestionsVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationQuestionsData>): UseDataConnectQueryResult<GetStudentEvaluationQuestionsData, GetStudentEvaluationQuestionsVariables>;

export function useGetStudentAnswerOptions(vars: GetStudentAnswerOptionsVariables, options?: useDataConnectQueryOptions<GetStudentAnswerOptionsData>): UseDataConnectQueryResult<GetStudentAnswerOptionsData, GetStudentAnswerOptionsVariables>;
export function useGetStudentAnswerOptions(dc: DataConnect, vars: GetStudentAnswerOptionsVariables, options?: useDataConnectQueryOptions<GetStudentAnswerOptionsData>): UseDataConnectQueryResult<GetStudentAnswerOptionsData, GetStudentAnswerOptionsVariables>;

export function useGetStudentEvaluationsByCourseEvaluation(vars: GetStudentEvaluationsByCourseEvaluationVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByCourseEvaluationData>): UseDataConnectQueryResult<GetStudentEvaluationsByCourseEvaluationData, GetStudentEvaluationsByCourseEvaluationVariables>;
export function useGetStudentEvaluationsByCourseEvaluation(dc: DataConnect, vars: GetStudentEvaluationsByCourseEvaluationVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByCourseEvaluationData>): UseDataConnectQueryResult<GetStudentEvaluationsByCourseEvaluationData, GetStudentEvaluationsByCourseEvaluationVariables>;

export function useGetStudentEvaluationsByCourseStudent(vars: GetStudentEvaluationsByCourseStudentVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByCourseStudentData>): UseDataConnectQueryResult<GetStudentEvaluationsByCourseStudentData, GetStudentEvaluationsByCourseStudentVariables>;
export function useGetStudentEvaluationsByCourseStudent(dc: DataConnect, vars: GetStudentEvaluationsByCourseStudentVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationsByCourseStudentData>): UseDataConnectQueryResult<GetStudentEvaluationsByCourseStudentData, GetStudentEvaluationsByCourseStudentVariables>;

export function useGetStudentEvaluationFullDetail(vars: GetStudentEvaluationFullDetailVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationFullDetailData>): UseDataConnectQueryResult<GetStudentEvaluationFullDetailData, GetStudentEvaluationFullDetailVariables>;
export function useGetStudentEvaluationFullDetail(dc: DataConnect, vars: GetStudentEvaluationFullDetailVariables, options?: useDataConnectQueryOptions<GetStudentEvaluationFullDetailData>): UseDataConnectQueryResult<GetStudentEvaluationFullDetailData, GetStudentEvaluationFullDetailVariables>;

export function useGetCourseEvaluationsByUser(vars: GetCourseEvaluationsByUserVariables, options?: useDataConnectQueryOptions<GetCourseEvaluationsByUserData>): UseDataConnectQueryResult<GetCourseEvaluationsByUserData, GetCourseEvaluationsByUserVariables>;
export function useGetCourseEvaluationsByUser(dc: DataConnect, vars: GetCourseEvaluationsByUserVariables, options?: useDataConnectQueryOptions<GetCourseEvaluationsByUserData>): UseDataConnectQueryResult<GetCourseEvaluationsByUserData, GetCourseEvaluationsByUserVariables>;

export function useGetCourseEvaluationById(vars: GetCourseEvaluationByIdVariables, options?: useDataConnectQueryOptions<GetCourseEvaluationByIdData>): UseDataConnectQueryResult<GetCourseEvaluationByIdData, GetCourseEvaluationByIdVariables>;
export function useGetCourseEvaluationById(dc: DataConnect, vars: GetCourseEvaluationByIdVariables, options?: useDataConnectQueryOptions<GetCourseEvaluationByIdData>): UseDataConnectQueryResult<GetCourseEvaluationByIdData, GetCourseEvaluationByIdVariables>;

export function useGetEvaluationsForCourse(vars: GetEvaluationsForCourseVariables, options?: useDataConnectQueryOptions<GetEvaluationsForCourseData>): UseDataConnectQueryResult<GetEvaluationsForCourseData, GetEvaluationsForCourseVariables>;
export function useGetEvaluationsForCourse(dc: DataConnect, vars: GetEvaluationsForCourseVariables, options?: useDataConnectQueryOptions<GetEvaluationsForCourseData>): UseDataConnectQueryResult<GetEvaluationsForCourseData, GetEvaluationsForCourseVariables>;

export function useGetCoursesForEvaluation(vars: GetCoursesForEvaluationVariables, options?: useDataConnectQueryOptions<GetCoursesForEvaluationData>): UseDataConnectQueryResult<GetCoursesForEvaluationData, GetCoursesForEvaluationVariables>;
export function useGetCoursesForEvaluation(dc: DataConnect, vars: GetCoursesForEvaluationVariables, options?: useDataConnectQueryOptions<GetCoursesForEvaluationData>): UseDataConnectQueryResult<GetCoursesForEvaluationData, GetCoursesForEvaluationVariables>;
