extend type Mutation {
  """
  ✨ Insert a single `Course` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  course_insert(
    """
    Data object to insert into the table.
    """
    data: Course_Data!
  ): Course_KeyOutput! @fdc_generated(from: "Course", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CourseEvaluation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseEvaluation_insert(
    """
    Data object to insert into the table.
    """
    data: CourseEvaluation_Data!
  ): CourseEvaluation_KeyOutput! @fdc_generated(from: "CourseEvaluation", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CourseStudent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseStudent_insert(
    """
    Data object to insert into the table.
    """
    data: CourseStudent_Data!
  ): CourseStudent_KeyOutput! @fdc_generated(from: "CourseStudent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Difficulty` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  difficulty_insert(
    """
    Data object to insert into the table.
    """
    data: Difficulty_Data!
  ): Difficulty_KeyOutput! @fdc_generated(from: "Difficulty", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `EducationalLevel` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  educationalLevel_insert(
    """
    Data object to insert into the table.
    """
    data: EducationalLevel_Data!
  ): EducationalLevel_KeyOutput! @fdc_generated(from: "EducationalLevel", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Evaluation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  evaluation_insert(
    """
    Data object to insert into the table.
    """
    data: Evaluation_Data!
  ): Evaluation_KeyOutput! @fdc_generated(from: "Evaluation", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `EvaluationQuestion` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  evaluationQuestion_insert(
    """
    Data object to insert into the table.
    """
    data: EvaluationQuestion_Data!
  ): EvaluationQuestion_KeyOutput! @fdc_generated(from: "EvaluationQuestion", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LevelCategory` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  levelCategory_insert(
    """
    Data object to insert into the table.
    """
    data: LevelCategory_Data!
  ): LevelCategory_KeyOutput! @fdc_generated(from: "LevelCategory", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Question` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  question_insert(
    """
    Data object to insert into the table.
    """
    data: Question_Data!
  ): Question_KeyOutput! @fdc_generated(from: "Question", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `QuestionOption` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  questionOption_insert(
    """
    Data object to insert into the table.
    """
    data: QuestionOption_Data!
  ): QuestionOption_KeyOutput! @fdc_generated(from: "QuestionOption", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `QuestionType` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  questionType_insert(
    """
    Data object to insert into the table.
    """
    data: QuestionType_Data!
  ): QuestionType_KeyOutput! @fdc_generated(from: "QuestionType", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Student` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insert(
    """
    Data object to insert into the table.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentAnswerOption` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentAnswerOption_insert(
    """
    Data object to insert into the table.
    """
    data: StudentAnswerOption_Data!
  ): StudentAnswerOption_KeyOutput! @fdc_generated(from: "StudentAnswerOption", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentCourseEvaluation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentCourseEvaluation_insert(
    """
    Data object to insert into the table.
    """
    data: StudentCourseEvaluation_Data!
  ): StudentCourseEvaluation_KeyOutput! @fdc_generated(from: "StudentCourseEvaluation", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentEvaluationQuestion` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentEvaluationQuestion_insert(
    """
    Data object to insert into the table.
    """
    data: StudentEvaluationQuestion_Data!
  ): StudentEvaluationQuestion_KeyOutput! @fdc_generated(from: "StudentEvaluationQuestion", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Subject` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subject_insert(
    """
    Data object to insert into the table.
    """
    data: Subject_Data!
  ): Subject_KeyOutput! @fdc_generated(from: "Subject", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Taxonomy` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  taxonomy_insert(
    """
    Data object to insert into the table.
    """
    data: Taxonomy_Data!
  ): Taxonomy_KeyOutput! @fdc_generated(from: "Taxonomy", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Topic` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  topic_insert(
    """
    Data object to insert into the table.
    """
    data: Topic_Data!
  ): Topic_KeyOutput! @fdc_generated(from: "Topic", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Unit` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  unit_insert(
    """
    Data object to insert into the table.
    """
    data: Unit_Data!
  ): Unit_KeyOutput! @fdc_generated(from: "Unit", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Course` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  course_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Course_Data!]!
  ): [Course_KeyOutput!]! @fdc_generated(from: "Course", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CourseEvaluation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseEvaluation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CourseEvaluation_Data!]!
  ): [CourseEvaluation_KeyOutput!]! @fdc_generated(from: "CourseEvaluation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CourseStudent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  courseStudent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CourseStudent_Data!]!
  ): [CourseStudent_KeyOutput!]! @fdc_generated(from: "CourseStudent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Difficulty` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  difficulty_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Difficulty_Data!]!
  ): [Difficulty_KeyOutput!]! @fdc_generated(from: "Difficulty", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `EducationalLevel` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  educationalLevel_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [EducationalLevel_Data!]!
  ): [EducationalLevel_KeyOutput!]! @fdc_generated(from: "EducationalLevel", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Evaluation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  evaluation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Evaluation_Data!]!
  ): [Evaluation_KeyOutput!]! @fdc_generated(from: "Evaluation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `EvaluationQuestion` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  evaluationQuestion_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [EvaluationQuestion_Data!]!
  ): [EvaluationQuestion_KeyOutput!]! @fdc_generated(from: "EvaluationQuestion", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LevelCategory` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  levelCategory_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LevelCategory_Data!]!
  ): [LevelCategory_KeyOutput!]! @fdc_generated(from: "LevelCategory", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Question` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  question_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Question_Data!]!
  ): [Question_KeyOutput!]! @fdc_generated(from: "Question", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `QuestionOption` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  questionOption_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [QuestionOption_Data!]!
  ): [QuestionOption_KeyOutput!]! @fdc_generated(from: "QuestionOption", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `QuestionType` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  questionType_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [QuestionType_Data!]!
  ): [QuestionType_KeyOutput!]! @fdc_generated(from: "QuestionType", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Student` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentAnswerOption` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentAnswerOption_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentAnswerOption_Data!]!
  ): [StudentAnswerOption_KeyOutput!]! @fdc_generated(from: "StudentAnswerOption", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentCourseEvaluation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentCourseEvaluation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentCourseEvaluation_Data!]!
  ): [StudentCourseEvaluation_KeyOutput!]! @fdc_generated(from: "StudentCourseEvaluation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentEvaluationQuestion` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentEvaluationQuestion_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentEvaluationQuestion_Data!]!
  ): [StudentEvaluationQuestion_KeyOutput!]! @fdc_generated(from: "StudentEvaluationQuestion", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Subject` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subject_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Subject_Data!]!
  ): [Subject_KeyOutput!]! @fdc_generated(from: "Subject", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Taxonomy` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  taxonomy_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Taxonomy_Data!]!
  ): [Taxonomy_KeyOutput!]! @fdc_generated(from: "Taxonomy", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Topic` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  topic_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Topic_Data!]!
  ): [Topic_KeyOutput!]! @fdc_generated(from: "Topic", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Unit` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  unit_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Unit_Data!]!
  ): [Unit_KeyOutput!]! @fdc_generated(from: "Unit", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Course` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Course`.
  """
  course_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Course_Data!
  ): Course_KeyOutput! @fdc_generated(from: "Course", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CourseEvaluation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseEvaluation`.
  """
  courseEvaluation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CourseEvaluation_Data!
  ): CourseEvaluation_KeyOutput! @fdc_generated(from: "CourseEvaluation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CourseStudent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseStudent`.
  """
  courseStudent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CourseStudent_Data!
  ): CourseStudent_KeyOutput! @fdc_generated(from: "CourseStudent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Difficulty` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Difficulty`.
  """
  difficulty_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Difficulty_Data!
  ): Difficulty_KeyOutput! @fdc_generated(from: "Difficulty", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `EducationalLevel` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EducationalLevel`.
  """
  educationalLevel_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: EducationalLevel_Data!
  ): EducationalLevel_KeyOutput! @fdc_generated(from: "EducationalLevel", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Evaluation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Evaluation`.
  """
  evaluation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Evaluation_Data!
  ): Evaluation_KeyOutput! @fdc_generated(from: "Evaluation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `EvaluationQuestion` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EvaluationQuestion`.
  """
  evaluationQuestion_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: EvaluationQuestion_Data!
  ): EvaluationQuestion_KeyOutput! @fdc_generated(from: "EvaluationQuestion", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LevelCategory` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LevelCategory`.
  """
  levelCategory_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LevelCategory_Data!
  ): LevelCategory_KeyOutput! @fdc_generated(from: "LevelCategory", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Question` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Question`.
  """
  question_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Question_Data!
  ): Question_KeyOutput! @fdc_generated(from: "Question", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `QuestionOption` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuestionOption`.
  """
  questionOption_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: QuestionOption_Data!
  ): QuestionOption_KeyOutput! @fdc_generated(from: "QuestionOption", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `QuestionType` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuestionType`.
  """
  questionType_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: QuestionType_Data!
  ): QuestionType_KeyOutput! @fdc_generated(from: "QuestionType", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Student` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentAnswerOption` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentAnswerOption`.
  """
  studentAnswerOption_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentAnswerOption_Data!
  ): StudentAnswerOption_KeyOutput! @fdc_generated(from: "StudentAnswerOption", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentCourseEvaluation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentCourseEvaluation`.
  """
  studentCourseEvaluation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentCourseEvaluation_Data!
  ): StudentCourseEvaluation_KeyOutput! @fdc_generated(from: "StudentCourseEvaluation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentEvaluationQuestion` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentEvaluationQuestion`.
  """
  studentEvaluationQuestion_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentEvaluationQuestion_Data!
  ): StudentEvaluationQuestion_KeyOutput! @fdc_generated(from: "StudentEvaluationQuestion", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Subject` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Subject`.
  """
  subject_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Subject_Data!
  ): Subject_KeyOutput! @fdc_generated(from: "Subject", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Taxonomy` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Taxonomy`.
  """
  taxonomy_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Taxonomy_Data!
  ): Taxonomy_KeyOutput! @fdc_generated(from: "Taxonomy", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Topic` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Topic`.
  """
  topic_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Topic_Data!
  ): Topic_KeyOutput! @fdc_generated(from: "Topic", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Unit` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Unit`.
  """
  unit_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Unit_Data!
  ): Unit_KeyOutput! @fdc_generated(from: "Unit", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Course` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Course`.
  """
  course_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Course_Data!]!
  ): [Course_KeyOutput!]! @fdc_generated(from: "Course", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CourseEvaluation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseEvaluation`.
  """
  courseEvaluation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CourseEvaluation_Data!]!
  ): [CourseEvaluation_KeyOutput!]! @fdc_generated(from: "CourseEvaluation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CourseStudent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CourseStudent`.
  """
  courseStudent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CourseStudent_Data!]!
  ): [CourseStudent_KeyOutput!]! @fdc_generated(from: "CourseStudent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Difficulty` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Difficulty`.
  """
  difficulty_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Difficulty_Data!]!
  ): [Difficulty_KeyOutput!]! @fdc_generated(from: "Difficulty", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `EducationalLevel` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EducationalLevel`.
  """
  educationalLevel_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [EducationalLevel_Data!]!
  ): [EducationalLevel_KeyOutput!]! @fdc_generated(from: "EducationalLevel", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Evaluation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Evaluation`.
  """
  evaluation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Evaluation_Data!]!
  ): [Evaluation_KeyOutput!]! @fdc_generated(from: "Evaluation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `EvaluationQuestion` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EvaluationQuestion`.
  """
  evaluationQuestion_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [EvaluationQuestion_Data!]!
  ): [EvaluationQuestion_KeyOutput!]! @fdc_generated(from: "EvaluationQuestion", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LevelCategory` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LevelCategory`.
  """
  levelCategory_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LevelCategory_Data!]!
  ): [LevelCategory_KeyOutput!]! @fdc_generated(from: "LevelCategory", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Question` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Question`.
  """
  question_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Question_Data!]!
  ): [Question_KeyOutput!]! @fdc_generated(from: "Question", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `QuestionOption` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuestionOption`.
  """
  questionOption_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [QuestionOption_Data!]!
  ): [QuestionOption_KeyOutput!]! @fdc_generated(from: "QuestionOption", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `QuestionType` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuestionType`.
  """
  questionType_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [QuestionType_Data!]!
  ): [QuestionType_KeyOutput!]! @fdc_generated(from: "QuestionType", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Student` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentAnswerOption` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentAnswerOption`.
  """
  studentAnswerOption_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentAnswerOption_Data!]!
  ): [StudentAnswerOption_KeyOutput!]! @fdc_generated(from: "StudentAnswerOption", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentCourseEvaluation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentCourseEvaluation`.
  """
  studentCourseEvaluation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentCourseEvaluation_Data!]!
  ): [StudentCourseEvaluation_KeyOutput!]! @fdc_generated(from: "StudentCourseEvaluation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentEvaluationQuestion` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentEvaluationQuestion`.
  """
  studentEvaluationQuestion_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentEvaluationQuestion_Data!]!
  ): [StudentEvaluationQuestion_KeyOutput!]! @fdc_generated(from: "StudentEvaluationQuestion", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Subject` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Subject`.
  """
  subject_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Subject_Data!]!
  ): [Subject_KeyOutput!]! @fdc_generated(from: "Subject", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Taxonomy` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Taxonomy`.
  """
  taxonomy_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Taxonomy_Data!]!
  ): [Taxonomy_KeyOutput!]! @fdc_generated(from: "Taxonomy", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Topic` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Topic`.
  """
  topic_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Topic_Data!]!
  ): [Topic_KeyOutput!]! @fdc_generated(from: "Topic", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Unit` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Unit`.
  """
  unit_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Unit_Data!]!
  ): [Unit_KeyOutput!]! @fdc_generated(from: "Unit", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Course` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Course` or `null` if not found.
  """
  course_update(
    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Course_Data!
  ): Course_KeyOutput @fdc_generated(from: "Course", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CourseEvaluation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CourseEvaluation` or `null` if not found.
  """
  courseEvaluation_update(
    """
    The key used to identify the object.
    """
    key: CourseEvaluation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseEvaluation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CourseEvaluation_Data!
  ): CourseEvaluation_KeyOutput @fdc_generated(from: "CourseEvaluation", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CourseStudent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CourseStudent` or `null` if not found.
  """
  courseStudent_update(
    """
    The key used to identify the object.
    """
    key: CourseStudent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseStudent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CourseStudent_Data!
  ): CourseStudent_KeyOutput @fdc_generated(from: "CourseStudent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Difficulty` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Difficulty` or `null` if not found.
  """
  difficulty_update(
    """
    The key used to identify the object.
    """
    key: Difficulty_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Difficulty_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Difficulty_Data!
  ): Difficulty_KeyOutput @fdc_generated(from: "Difficulty", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `EducationalLevel` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `EducationalLevel` or `null` if not found.
  """
  educationalLevel_update(
    """
    The key used to identify the object.
    """
    key: EducationalLevel_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EducationalLevel_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: EducationalLevel_Data!
  ): EducationalLevel_KeyOutput @fdc_generated(from: "EducationalLevel", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Evaluation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Evaluation` or `null` if not found.
  """
  evaluation_update(
    """
    The key used to identify the object.
    """
    key: Evaluation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Evaluation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Evaluation_Data!
  ): Evaluation_KeyOutput @fdc_generated(from: "Evaluation", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `EvaluationQuestion` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `EvaluationQuestion` or `null` if not found.
  """
  evaluationQuestion_update(
    """
    The key used to identify the object.
    """
    key: EvaluationQuestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EvaluationQuestion_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: EvaluationQuestion_Data!
  ): EvaluationQuestion_KeyOutput @fdc_generated(from: "EvaluationQuestion", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LevelCategory` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LevelCategory` or `null` if not found.
  """
  levelCategory_update(
    """
    The key used to identify the object.
    """
    key: LevelCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LevelCategory_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LevelCategory_Data!
  ): LevelCategory_KeyOutput @fdc_generated(from: "LevelCategory", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Question` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Question` or `null` if not found.
  """
  question_update(
    """
    The key used to identify the object.
    """
    key: Question_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Question_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Question_Data!
  ): Question_KeyOutput @fdc_generated(from: "Question", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `QuestionOption` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `QuestionOption` or `null` if not found.
  """
  questionOption_update(
    """
    The key used to identify the object.
    """
    key: QuestionOption_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuestionOption_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: QuestionOption_Data!
  ): QuestionOption_KeyOutput @fdc_generated(from: "QuestionOption", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `QuestionType` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `QuestionType` or `null` if not found.
  """
  questionType_update(
    """
    The key used to identify the object.
    """
    key: QuestionType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuestionType_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: QuestionType_Data!
  ): QuestionType_KeyOutput @fdc_generated(from: "QuestionType", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Student` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Student` or `null` if not found.
  """
  student_update(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Student_Data!
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentAnswerOption` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentAnswerOption` or `null` if not found.
  """
  studentAnswerOption_update(
    """
    The key used to identify the object.
    """
    key: StudentAnswerOption_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentAnswerOption_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentAnswerOption_Data!
  ): StudentAnswerOption_KeyOutput @fdc_generated(from: "StudentAnswerOption", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentCourseEvaluation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentCourseEvaluation` or `null` if not found.
  """
  studentCourseEvaluation_update(
    """
    The key used to identify the object.
    """
    key: StudentCourseEvaluation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentCourseEvaluation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentCourseEvaluation_Data!
  ): StudentCourseEvaluation_KeyOutput @fdc_generated(from: "StudentCourseEvaluation", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentEvaluationQuestion` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentEvaluationQuestion` or `null` if not found.
  """
  studentEvaluationQuestion_update(
    """
    The key used to identify the object.
    """
    key: StudentEvaluationQuestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentEvaluationQuestion_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentEvaluationQuestion_Data!
  ): StudentEvaluationQuestion_KeyOutput @fdc_generated(from: "StudentEvaluationQuestion", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Subject` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Subject` or `null` if not found.
  """
  subject_update(
    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Subject_Data!
  ): Subject_KeyOutput @fdc_generated(from: "Subject", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Taxonomy` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Taxonomy` or `null` if not found.
  """
  taxonomy_update(
    """
    The key used to identify the object.
    """
    key: Taxonomy_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Taxonomy_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Taxonomy_Data!
  ): Taxonomy_KeyOutput @fdc_generated(from: "Taxonomy", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Topic` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Topic` or `null` if not found.
  """
  topic_update(
    """
    The key used to identify the object.
    """
    key: Topic_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Topic_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Topic_Data!
  ): Topic_KeyOutput @fdc_generated(from: "Topic", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Unit` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Unit` or `null` if not found.
  """
  unit_update(
    """
    The key used to identify the object.
    """
    key: Unit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Unit_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Unit_Data!
  ): Unit_KeyOutput @fdc_generated(from: "Unit", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Course` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  course_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Course_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Course_Data!
  ): Int! @fdc_generated(from: "Course", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CourseEvaluation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  courseEvaluation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CourseEvaluation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CourseEvaluation_Data!
  ): Int! @fdc_generated(from: "CourseEvaluation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CourseStudent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  courseStudent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CourseStudent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CourseStudent_Data!
  ): Int! @fdc_generated(from: "CourseStudent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Difficulty` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  difficulty_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Difficulty_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Difficulty_Data!
  ): Int! @fdc_generated(from: "Difficulty", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `EducationalLevel` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  educationalLevel_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: EducationalLevel_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: EducationalLevel_Data!
  ): Int! @fdc_generated(from: "EducationalLevel", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Evaluation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  evaluation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Evaluation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Evaluation_Data!
  ): Int! @fdc_generated(from: "Evaluation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `EvaluationQuestion` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  evaluationQuestion_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: EvaluationQuestion_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: EvaluationQuestion_Data!
  ): Int! @fdc_generated(from: "EvaluationQuestion", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LevelCategory` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  levelCategory_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LevelCategory_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LevelCategory_Data!
  ): Int! @fdc_generated(from: "LevelCategory", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Question` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  question_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Question_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Question_Data!
  ): Int! @fdc_generated(from: "Question", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `QuestionOption` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  questionOption_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: QuestionOption_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: QuestionOption_Data!
  ): Int! @fdc_generated(from: "QuestionOption", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `QuestionType` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  questionType_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: QuestionType_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: QuestionType_Data!
  ): Int! @fdc_generated(from: "QuestionType", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Student` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  student_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Student_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Student_Data!
  ): Int! @fdc_generated(from: "Student", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentAnswerOption` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentAnswerOption_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentAnswerOption_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentAnswerOption_Data!
  ): Int! @fdc_generated(from: "StudentAnswerOption", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentCourseEvaluation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentCourseEvaluation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentCourseEvaluation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentCourseEvaluation_Data!
  ): Int! @fdc_generated(from: "StudentCourseEvaluation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentEvaluationQuestion` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentEvaluationQuestion_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentEvaluationQuestion_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentEvaluationQuestion_Data!
  ): Int! @fdc_generated(from: "StudentEvaluationQuestion", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Subject` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  subject_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Subject_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Subject_Data!
  ): Int! @fdc_generated(from: "Subject", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Taxonomy` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  taxonomy_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Taxonomy_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Taxonomy_Data!
  ): Int! @fdc_generated(from: "Taxonomy", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Topic` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  topic_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Topic_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Topic_Data!
  ): Int! @fdc_generated(from: "Topic", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Unit` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  unit_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Unit_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Unit_Data!
  ): Int! @fdc_generated(from: "Unit", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Course` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  course_delete(
    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow
  ): Course_KeyOutput @fdc_generated(from: "Course", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CourseEvaluation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  courseEvaluation_delete(
    """
    The key used to identify the object.
    """
    key: CourseEvaluation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseEvaluation_FirstRow
  ): CourseEvaluation_KeyOutput @fdc_generated(from: "CourseEvaluation", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CourseStudent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  courseStudent_delete(
    """
    The key used to identify the object.
    """
    key: CourseStudent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CourseStudent_FirstRow
  ): CourseStudent_KeyOutput @fdc_generated(from: "CourseStudent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Difficulty` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  difficulty_delete(
    """
    The key used to identify the object.
    """
    key: Difficulty_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Difficulty_FirstRow
  ): Difficulty_KeyOutput @fdc_generated(from: "Difficulty", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `EducationalLevel` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  educationalLevel_delete(
    """
    The key used to identify the object.
    """
    key: EducationalLevel_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EducationalLevel_FirstRow
  ): EducationalLevel_KeyOutput @fdc_generated(from: "EducationalLevel", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Evaluation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  evaluation_delete(
    """
    The key used to identify the object.
    """
    key: Evaluation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Evaluation_FirstRow
  ): Evaluation_KeyOutput @fdc_generated(from: "Evaluation", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `EvaluationQuestion` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  evaluationQuestion_delete(
    """
    The key used to identify the object.
    """
    key: EvaluationQuestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EvaluationQuestion_FirstRow
  ): EvaluationQuestion_KeyOutput @fdc_generated(from: "EvaluationQuestion", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LevelCategory` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  levelCategory_delete(
    """
    The key used to identify the object.
    """
    key: LevelCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LevelCategory_FirstRow
  ): LevelCategory_KeyOutput @fdc_generated(from: "LevelCategory", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Question` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  question_delete(
    """
    The key used to identify the object.
    """
    key: Question_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Question_FirstRow
  ): Question_KeyOutput @fdc_generated(from: "Question", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `QuestionOption` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  questionOption_delete(
    """
    The key used to identify the object.
    """
    key: QuestionOption_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuestionOption_FirstRow
  ): QuestionOption_KeyOutput @fdc_generated(from: "QuestionOption", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `QuestionType` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  questionType_delete(
    """
    The key used to identify the object.
    """
    key: QuestionType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuestionType_FirstRow
  ): QuestionType_KeyOutput @fdc_generated(from: "QuestionType", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Student` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  student_delete(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentAnswerOption` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentAnswerOption_delete(
    """
    The key used to identify the object.
    """
    key: StudentAnswerOption_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentAnswerOption_FirstRow
  ): StudentAnswerOption_KeyOutput @fdc_generated(from: "StudentAnswerOption", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentCourseEvaluation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentCourseEvaluation_delete(
    """
    The key used to identify the object.
    """
    key: StudentCourseEvaluation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentCourseEvaluation_FirstRow
  ): StudentCourseEvaluation_KeyOutput @fdc_generated(from: "StudentCourseEvaluation", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentEvaluationQuestion` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentEvaluationQuestion_delete(
    """
    The key used to identify the object.
    """
    key: StudentEvaluationQuestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentEvaluationQuestion_FirstRow
  ): StudentEvaluationQuestion_KeyOutput @fdc_generated(from: "StudentEvaluationQuestion", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Subject` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  subject_delete(
    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow
  ): Subject_KeyOutput @fdc_generated(from: "Subject", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Taxonomy` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  taxonomy_delete(
    """
    The key used to identify the object.
    """
    key: Taxonomy_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Taxonomy_FirstRow
  ): Taxonomy_KeyOutput @fdc_generated(from: "Taxonomy", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Topic` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  topic_delete(
    """
    The key used to identify the object.
    """
    key: Topic_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Topic_FirstRow
  ): Topic_KeyOutput @fdc_generated(from: "Topic", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Unit` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  unit_delete(
    """
    The key used to identify the object.
    """
    key: Unit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Unit_FirstRow
  ): Unit_KeyOutput @fdc_generated(from: "Unit", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Course` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  course_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Course_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Course", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CourseEvaluation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  courseEvaluation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CourseEvaluation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CourseEvaluation", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CourseStudent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  courseStudent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CourseStudent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CourseStudent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Difficulty` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  difficulty_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Difficulty_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Difficulty", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `EducationalLevel` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  educationalLevel_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: EducationalLevel_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "EducationalLevel", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Evaluation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  evaluation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Evaluation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Evaluation", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `EvaluationQuestion` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  evaluationQuestion_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: EvaluationQuestion_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "EvaluationQuestion", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LevelCategory` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  levelCategory_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LevelCategory_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LevelCategory", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Question` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  question_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Question_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Question", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `QuestionOption` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  questionOption_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: QuestionOption_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "QuestionOption", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `QuestionType` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  questionType_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: QuestionType_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "QuestionType", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Student` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  student_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Student_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Student", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentAnswerOption` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentAnswerOption_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentAnswerOption_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentAnswerOption", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentCourseEvaluation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentCourseEvaluation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentCourseEvaluation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentCourseEvaluation", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentEvaluationQuestion` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentEvaluationQuestion_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentEvaluationQuestion_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentEvaluationQuestion", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Subject` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  subject_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Subject_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Subject", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Taxonomy` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  taxonomy_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Taxonomy_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Taxonomy", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Topic` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  topic_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Topic_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Topic", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Unit` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  unit_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Unit_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Unit", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
